import { SUPPORTED_LANGUAGE_NAMES } from "../transcription/deepgram";

export interface VideoAnalysisData {
  title?: string;
  summary?: string;
  topics?: string[];
  keyMoments?: { timestamp: string; description: string }[];
  speakers?: { label: string; description?: string }[];
  sentiment?: string;
  tags?: string[];
  // Raw Gemini JSON — any additional fields from your existing analysis
  [key: string]: unknown;
}

export interface SystemPromptOptions {
  videoAnalysis: VideoAnalysisData | null;
  transcription: {
    formattedTranscript: string;
    detectedLanguage: string | null;
    confidence: number | null;
    wordCount: number;
  } | null;
  videoTitle?: string;
}

const SUPPORTED_LANGS_STRING = SUPPORTED_LANGUAGE_NAMES.join(", ");

/**
 * Builds the full system prompt injected before any conversation.
 * This is NOT stored in chat history — it's re-built each request.
 */
export function buildSystemPrompt(options: SystemPromptOptions): string {
  const { videoAnalysis, transcription, videoTitle } = options;

  const title = videoTitle || videoAnalysis?.title || "this video";

  // --- Language Warning Block ---
  const languageWarning = buildLanguageWarning(transcription?.detectedLanguage);

  // --- Video Analysis Block ---
  const analysisBlock = buildAnalysisBlock(videoAnalysis, title);

  // --- Transcript Block ---
  const transcriptBlock = buildTranscriptBlock(transcription);

  // --- Assemble ---
  return `You are an intelligent video analysis assistant for Alyzitron, an AI-powered video analysis platform.

Your role is to help users understand, explore, and extract insights from video content based on AI-generated analysis and a full transcript.

${languageWarning}

---

## VIDEO INFORMATION
Title: ${title}

${analysisBlock}

---

${transcriptBlock}

---

## BEHAVIOR GUIDELINES

1. **Accuracy First**: Only answer based on the video analysis and transcript provided. Do not hallucinate content not present in these sources.

2. **Cite Evidence**: When making claims, reference specific timestamps, speaker labels, or analysis data when available.

3. **Speaker Awareness**: The transcript includes speaker diarization (Speaker A, Speaker B, etc.). Reference speakers by their label or inferred role when discussing dialogue.

4. **Timestamps**: When users ask about specific moments, provide the [MM:SS] timestamp from the transcript.

5. **Scope**: If asked something completely unrelated to the video, gently redirect and focus on what the video content covers.

6. **Tone**: Be analytical, helpful, and concise. You can be conversational but stay focused.

7. **No Analysis Tool Access**: You cannot re-run analysis. You work with the pre-generated data above.`;
}

function buildLanguageWarning(detectedLanguage: string | null): string {
  if (!detectedLanguage) {
    return `⚠️ **LANGUAGE NOTE**: The video's language could not be detected or transcription was not available. 
Transcription and analysis accuracy are supported for the following languages: ${SUPPORTED_LANGS_STRING}.
If this video is in an unsupported language, the AI may not be able to answer questions accurately about its content.`;
  }

  const isSupported = SUPPORTED_LANGUAGE_NAMES.some(
    (lang) =>
      lang.toLowerCase().includes(detectedLanguage.toLowerCase()) ||
      detectedLanguage.toLowerCase().startsWith(lang.slice(0, 2).toLowerCase())
  );

  if (!isSupported) {
    return `⚠️ **LANGUAGE WARNING**: This video appears to be in **${detectedLanguage}**, which may not be fully supported by the transcription system.
Supported languages are: ${SUPPORTED_LANGS_STRING}.
The transcript and analysis may be incomplete or inaccurate. Answer with appropriate caveats about transcription quality.`;
  }

  return `ℹ️ **Language**: This video is in **${detectedLanguage}** (supported). Transcription confidence is high.`;
}

function buildAnalysisBlock(
  analysis: VideoAnalysisData | null,
  title: string
): string {
  if (!analysis) {
    return "## AI VIDEO ANALYSIS\n_No analysis data available for this video._";
  }

  const lines: string[] = ["## AI VIDEO ANALYSIS (Generated by Gemini)"];

  if (analysis.summary) {
    lines.push(`\n### Summary\n${analysis.summary}`);
  }

  if (analysis.topics?.length) {
    lines.push(`\n### Key Topics\n${analysis.topics.map((t) => `- ${t}`).join("\n")}`);
  }

  if (analysis.keyMoments?.length) {
    lines.push(`\n### Key Moments`);
    analysis.keyMoments.forEach((m) => {
      lines.push(`- **${m.timestamp}** — ${m.description}`);
    });
  }

  if (analysis.speakers?.length) {
    lines.push(`\n### Identified Speakers`);
    analysis.speakers.forEach((s) => {
      lines.push(`- **${s.label}**${s.description ? `: ${s.description}` : ""}`);
    });
  }

  if (analysis.sentiment) {
    lines.push(`\n### Overall Sentiment\n${analysis.sentiment}`);
  }

  if (analysis.tags?.length) {
    lines.push(`\n### Tags\n${analysis.tags.join(", ")}`);
  }

  // Append remaining raw fields (not already handled)
  const handledKeys = new Set([
    "title", "summary", "topics", "keyMoments", "speakers", "sentiment", "tags",
  ]);
  const extraEntries = Object.entries(analysis).filter(
    ([k]) => !handledKeys.has(k) && analysis[k] !== undefined
  );

  if (extraEntries.length > 0) {
    lines.push(`\n### Additional Analysis Data`);
    lines.push("```json");
    lines.push(JSON.stringify(Object.fromEntries(extraEntries), null, 2));
    lines.push("```");
  }

  return lines.join("\n");
}

function buildTranscriptBlock(
  transcription: SystemPromptOptions["transcription"]
): string {
  if (!transcription || !transcription.formattedTranscript) {
    return `## FULL TRANSCRIPT\n_Transcript not available. Answer based on the video analysis data only._`;
  }

  const meta = [
    transcription.wordCount ? `Words: ${transcription.wordCount}` : null,
    transcription.confidence
      ? `Transcription Confidence: ${Math.round(transcription.confidence * 100)}%`
      : null,
  ]
    .filter(Boolean)
    .join(" | ");

  return `## FULL TRANSCRIPT WITH SPEAKER DIARIZATION
${meta ? `_(${meta})_\n` : ""}
Format: [MM:SS] Speaker X: text

${transcription.formattedTranscript}`;
}