steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.explainer-worker', '-t', 'us-central1-docker.pkg.dev/insturix-493414/editron/explainer-worker:latest', '.']
images:
  - 'us-central1-docker.pkg.dev/insturix-493414/editron/explainer-worker:latest'
timeout: '1800s'
options:
  machineType: 'E2_HIGHCPU_8'
