# VO-DRIVEN TIMING. The correct order: synth the narration FIRST, measure each line, then make each scene
# long enough to HOLD its own line (+ a reading pad). Rewrites out/plan.json durations and regenerates
# src/bricks/generated-plan.ts so the render matches. Fixes the "all voices overlap" bug at the root.
import json, os, subprocess, asyncio, math
import edge_tts

VOICE = os.environ.get('EXPLAINER_VOICE', 'en-US-AvaNeural')   # any edge-tts voice id (see vo-voices catalog)
RATE = os.environ.get('EXPLAINER_VOICE_RATE', '-4%')
MIN_SEC = 2.6   # floor so short lines still breathe
PAD_SEC = 0.9   # silence after a line before the next scene (a beat to land)

plan = json.load(open('out/plan.json', encoding='utf-8'))
fps, scenes = plan['fps'], plan['scenes']
os.makedirs('out/vo/glm', exist_ok=True)

def dur(p):
    return float(subprocess.check_output(['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', p]).decode().strip())

async def main():
    for i, s in enumerate(scenes):
        vo = (s.get('vo') or '').strip()
        if vo:
            p = 'out/vo/glm/%d.mp3' % i
            await edge_tts.Communicate(vo, VOICE, rate=RATE).save(p)
            s['durationInFrames'] = int(math.ceil(max(MIN_SEC, dur(p) + PAD_SEC) * fps))
        else:
            s['durationInFrames'] = int(math.ceil(MIN_SEC * fps))

asyncio.run(main())

json.dump(plan, open('out/plan.json', 'w', encoding='utf-8'), indent=2)

scenes_ts = [{'form': s['form'], 'durationInFrames': s['durationInFrames'], 'vo': s.get('vo', ''), 'props': s.get('props', {})} for s in scenes]
ts = ('// AUTO-GENERATED by scripts/glm-voice-fit.py — durations fitted to the VO. Do not edit by hand.\n'
      "import type {SceneSpec} from './scene-graph';\n"
      'export const GENERATED_MESSAGE = %s;\n'
      'export const GENERATED_SCENES: SceneSpec[] = %s as SceneSpec[];\n' % (json.dumps(plan.get('message', '')), json.dumps(scenes_ts, indent=2)))
open('src/bricks/generated-plan.ts', 'w', encoding='utf-8').write(ts)

T = plan['transitionFrames']
total = sum(s['durationInFrames'] for s in scenes) - T * (len(scenes) - 1)
print('Fitted scene durations to VO:')
for i, s in enumerate(scenes):
    print('  %d. %-6s %3df (%.2fs)  vo=%.2fs' % (i + 1, s['form'], s['durationInFrames'], s['durationInFrames'] / fps, dur('out/vo/glm/%d.mp3' % i) if (s.get('vo') or '').strip() else 0))
print('film total = %.1fs' % (total / fps))
