// prep-audio.mjs — VO + music prep, run BEFORE craft (it fits scene durations to the narration).
//
// 1) synth Ava VO per scene + rewrite out/plan.json durations so each scene HOLDS its line (glm-voice-fit.py,
//    the proven audio-first timing step); 2) copy the VO clips into public/audio/vo-<i>.mp3 so the Remotion
//    site can staticFile() them; 3) write src/bricks/gen/audio-config.ts so Gen-Film mounts VO + a music bed.
// The result: ONE Lambda render produces the final film WITH sound (no post-mux / re-upload).
//
// DEPS on the worker box: python3 + `edge-tts` + ffmpeg/ffprobe (all already used by the standalone pipeline).
// No Anthropic/craft creds are spent here — VO is edge-tts (free).

import {spawnSync} from 'node:child_process';
import {existsSync, mkdirSync, copyFileSync, writeFileSync, readFileSync} from 'node:fs';
import {dirname} from 'node:path';

const CONFIG = 'src/bricks/gen/audio-config.ts';
const write = (music, voScenes) => {
  // src/bricks/gen/ is generated output (gitignored + excluded from the container image), so in a fresh render
  // box it does not exist yet — create it before writing, or writeFileSync ENOENTs and the whole render fails.
  mkdirSync(dirname(CONFIG), {recursive: true});
  writeFileSync(CONFIG,
    `// AUTO-GENERATED by scripts/prep-audio.mjs.\n` +
    `export const AUDIO: { music: string; musicVolume?: number; voScenes: number[] } = ${JSON.stringify({music, musicVolume: 0.16, voScenes})};\n`);
};

if (!existsSync('out/plan.json')) { console.error('prep-audio: out/plan.json missing.'); process.exit(1); }

// Reset to SILENT first, so a prep failure below leaves a clean silent film (never stale VO from a prior video).
write('', []);

// 1) synth + fit durations (try python3 then python). Soft-fail: no python/edge-tts → silent video, not a dead job.
let ran = null;
for (const py of [process.env.PYTHON, 'python3', 'python'].filter(Boolean)) {
  const r = spawnSync(py, ['scripts/glm-voice-fit.py'], {stdio: 'inherit'});
  if (r.error && r.error.code === 'ENOENT') continue; // interpreter not found, try next
  ran = r; break;
}
if (!ran) { console.warn('prep-audio: no python interpreter (need python3 + edge-tts) — rendering SILENT.'); process.exit(0); }
if (ran.status !== 0) { console.warn('prep-audio: glm-voice-fit.py failed — rendering SILENT.'); process.exit(0); }

// 2) copy VO clips into public/audio + collect which scenes have VO.
const plan = JSON.parse(readFileSync('out/plan.json', 'utf8'));
const scenes = plan.scenes || plan;
mkdirSync('public/audio', {recursive: true});
const voScenes = [];
scenes.forEach((s, i) => {
  const src = `out/vo/glm/${i}.mp3`;
  if ((s.vo || '').trim() && existsSync(src)) { copyFileSync(src, `public/audio/vo-${i}.mp3`); voScenes.push(i); }
});

// 3) music bed (ship a royalty-free loop in public/; CassetteAI-generated beds are the production upgrade).
const music = existsSync('public/music.mp3') ? 'music.mp3' : (existsSync('public/music-leskea.mp3') ? 'music-leskea.mp3' : '');

write(music, voScenes);
console.log(`prep-audio: ${voScenes.length} VO clip(s) + music=${music || 'none'} → ${CONFIG}`);
