import type {
  AudioRightsContract,
  MusicRightsContract,
} from "@/lib/editron/shared/render-request-payload";
import type { ProjectVideoSourceVersionPinV1 }
  from "@/lib/editron/services/project-video-source-version-pin-v1";
import type { GeneratedVideoReceipt } from "@/lib/pipeline/video-generation-service";

// Define overlay types enum
export enum OverlayType {
  TEXT = "text",
  IMAGE = "image",
  SHAPE = "shape",
  VIDEO = "video",
  SOUND = "sound",
  CAPTION = "caption",
  LOCAL_DIR = "local-dir",
  STICKER = "sticker",
  TEMPLATE = "template",
  AI_CHAT = "ai-chat", // AI Chat panel
  HTML_SCENE = "html-scene", // HTML generated content (backgrounds, diagrams)
  GENERATED_SCENE = "generated-scene", // Typed SaaS/product scene rendered by React
  HTML_STICKER = "html-sticker", // HTML generated stickers (transparent, animated elements)
  AI_SUGGESTIONS = "ai-suggestions", // AI Suggestions panel
  QUALITY_REVIEW = "quality-review", // Quality Review panel
  SCAN_REPORT = "scan-report",       // Director Mode scan report panel (sidebar)
  TRANSITIONS = "transitions",       // Transition browser panel (sidebar)
  SFX_LIBRARY = "sfx-library",       // SFX library browse panel (sidebar)
  LOTTIE = "lottie",                 // LottieFiles motion graphics panel (sidebar)
  TRANSITION = "transition",         // Actual transition overlay between clips (timeline item)
  MOTION_GRAPHIC = "motion-graphic", // React-rendered motion graphics (Structure � Theme system)
  MG_SEQUENCE = "mg-sequence",       // Full-frame transparent frame sequence generated by MG codegen
}
// --- Keyframe Animation System -----------------------------------
// Enables per-property animation curves on any overlay.
// Used by: dissolves, zoom effects, position animation, speed ramping.

export interface Keyframe {
  /** Local frame within the overlay (0 = overlay start) */
  frame: number;
  /** Value at this frame */
  value: number;
  /** Interpolation easing to the NEXT keyframe */
  easing: 'linear' | 'ease-in' | 'ease-out' | 'ease-in-out' | 'snap-out';
}

export interface KeyframeTrack {
  /**
   * Property to animate:
   * - x, y: absolute pixel position (same as overlay.left/overlay.top)
   * - scale: multiplier (1.0 = no change, 2.0 = double size)
   * - opacity: 0.0 (invisible) to 1.0 (fully visible)
   * - rotation: degrees
   * - speed: playback rate multiplier (0.25 to 4.0)
   * - objectPositionX/Y: video focal point in percent (0 to 100)
   */
  property: 'x' | 'y' | 'scale' | 'opacity' | 'rotation' | 'speed' | 'objectPositionX' | 'objectPositionY';
  keyframes: Keyframe[];
}

/** A user-authored named marker on the timeline (frame + label). D4. */
export interface NamedMarker {
  id: string;
  frame: number;
  label: string;
}

// Base overlay properties
type BaseOverlay = {
  id: number;
  durationInFrames: number;
  from: number;
  height: number;
  row: number;
  left: number;
  top: number;
  width: number;
  isDragging: boolean;
  rotation: number;
  type: OverlayType;
  assetId?: string; // GCS asset ID for media files (video, image, audio)
  /** Set on overlays inserted asynchronously so browser saves preserve them. */
  _workerAdded?: boolean;
  /** Per-property animation keyframe tracks (position, scale, opacity, etc.) */
  keyframeTracks?: KeyframeTrack[];
};

// Base style properties
type BaseStyles = {
  opacity?: number;
  zIndex?: number;
  transform?: string;
};

// Base animation type - extended to be compatible with CSSProperties potentially
export type AnimationConfig = {
  enter?: string;
  exit?: string;
  duration?: number;
};

// Text overlay specific
export type TextOverlay = BaseOverlay & {
  type: OverlayType.TEXT;
  content: string;
  styles: BaseStyles & {
    fontSize: string;
    fontWeight: string;
    color: string;
    backgroundColor: string;
    fontFamily: string;
    fontStyle: string;
    textDecoration: string;
    lineHeight?: string;
    letterSpacing?: string;
    textAlign?: "left" | "center" | "right";
    textShadow?: string;
    padding?: string;
    paddingBackgroundColor?: string;
    borderRadius?: string;
    boxShadow?: string;
    background?: string;
    WebkitBackgroundClip?: string;
    WebkitTextFillColor?: string;
    backdropFilter?: string;
    border?: string;
    animation?: AnimationConfig;
  };
};

// Shape overlay specific
export type ShapeOverlay = BaseOverlay & {
  type: OverlayType.SHAPE;
  content: string;
  styles: BaseStyles & {
    fill?: string;
    stroke?: string;
    strokeWidth?: number;
    borderRadius?: string;
    boxShadow?: string;
    gradient?: string;
  };
};

// Clip overlay specific
export type ClipOverlay = BaseOverlay & {
  type: OverlayType.VIDEO;
  content: string;
  src?: string; // Optional - resolved from assetId
  assetId?: string; // Reference to mediaAsset
  posterUrl?: string; // Storyboard image used as thumbnail fallback (avoids CORS)
  /** Inclusive source-frame start for exact source/timeline mapping. */
  sourceStartFrame?: number;
  /** Exclusive source-frame end for exact retime handle accounting. */
  sourceEndFrame?: number;
  /** ProjectService-owned proof of the exact proxy or master bytes addressed. */
  sourceVersionPinV1?: ProjectVideoSourceVersionPinV1;
  videoStartTime?: number;
  speed?: number;
  /** True if the video file contains embedded audio (e.g., Seedance 1.5 Pro).
   *  When true: Remotion's <Video> auto-plays the audio track.
   *  SFX generation is skipped for this scene. Audio ducking should duck
   *  native video audio under voiceover (same as BGM ducking). */
  hasNativeAudio?: boolean;
  /** Render/export rights for an embedded audio stream. Required when hasNativeAudio is true. */
  audioRights?: AudioRightsContract;
  /** Provider and FFmpeg-probe audit evidence for generated video. */
  generatedVideoReceipt?: GeneratedVideoReceipt;
  /** Variable speed curve � overrides constant `speed` when present.
   *  Each keyframe specifies a playback rate at a local frame offset.
   *  Video is split into segments, each with its own constant rate. */
  speedCurve?: Keyframe[];
  styles: BaseStyles & {
    objectFit?: "contain" | "cover" | "fill" | "none" | "scale-down";
    objectPosition?: string;
    volume?: number;
    borderRadius?: string;
    filter?: string;
    boxShadow?: string;
    border?: string;
    padding?: string;
    paddingBackgroundColor?: string;
    animation?: AnimationConfig; // Using shared type
  };
};

// Sound overlay specific
export type SoundOverlay = BaseOverlay & {
  type: OverlayType.SOUND;
  content: string;
  src?: string; // Optional - resolved from assetId
  assetId?: string; // Reference to mediaAsset
  /** Render/export licensing decision for SFX, voiceover, dubbing, and other audio. */
  audioRights?: AudioRightsContract;
  /** Render/export licensing decision for music and preview audio. */
  musicRights?: MusicRightsContract;
  /** Source-audio playback rate. Used for bounded phrase timing alignment. */
  playbackRate?: number;
  /** @deprecated Use audioStartFrame instead. Kept for backward compatibility. */
  startFromSound?: number;
  /** J-cut: audioStartFrame < overlay.from � audio begins before the video */
  audioStartFrame?: number;
  /** L-cut: audioEndFrame > overlay.from + durationInFrames � audio continues after video */
  audioEndFrame?: number;
  styles: BaseStyles & {
    volume?: number;
  };
};

export type CaptionWord = {
  word: string;
  startMs: number;
  endMs: number;
  confidence: number;
  emphasis?: {
    type: 'keyword' | 'statistic' | 'cta' | 'entity';
    source: string;
  };
};

export type Caption = {
  text: string;
  startMs: number;
  endMs: number;
  timestampMs: number | null;
  confidence: number | null;
  words: CaptionWord[];
};

// Caption display modes for different content types
export type CaptionDisplayMode = "word-by-word" | "phrase" | "karaoke" | "subtitle" | "instagram" | "hormozi";
export type CaptionEmphasisBehavior = "none" | "active-word";
export type CaptionFontSizing = "authored" | "box-relative";

/**
 * Display configuration for captions
 * Controls how words are grouped and displayed
 */
export interface CaptionDisplayConfig {
  /** Display mode */
  mode: CaptionDisplayMode;
  /** Number of words to show at once (1-12) */
  wordsPerGroup: number;
  /** Maximum words per line before wrapping */
  maxWordsPerLine: number;
  /** Keep previous words visible (progressive reveal) */
  showPreviousWords: boolean;
  /** Fade/dim previous words when progressive reveal is on */
  fadeOutPreviousWords: boolean;
  /** Whether timing should also produce per-word visual emphasis */
  emphasisBehavior?: CaptionEmphasisBehavior;
  /** Whether fontSize is final or should follow legacy box-resize scaling */
  fontSizing?: CaptionFontSizing;
  /** Use spring physics for active word scale (Remotion spring()) */
  useSpringScale?: boolean;
  /** Spring damping � lower = bouncier. Default 10. */
  springDamping?: number;
  /** Spring mass � higher = heavier/slower. Default 0.5. */
  springMass?: number;
}

/** Default display configs for each mode */
export const DEFAULT_DISPLAY_CONFIGS: Record<CaptionDisplayMode, CaptionDisplayConfig> = {
  "word-by-word": {
    mode: "word-by-word",
    wordsPerGroup: 1,
    maxWordsPerLine: 1,
    showPreviousWords: false,
    fadeOutPreviousWords: false,
  },
  "phrase": {
    mode: "phrase",
    wordsPerGroup: 4,
    maxWordsPerLine: 4,
    showPreviousWords: false,
    fadeOutPreviousWords: false,
  },
  "karaoke": {
    mode: "karaoke",
    wordsPerGroup: 5,
    maxWordsPerLine: 6,
    showPreviousWords: true,
    fadeOutPreviousWords: true,
  },
  "subtitle": {
    mode: "subtitle",
    wordsPerGroup: 10,
    maxWordsPerLine: 12,
    showPreviousWords: true,
    fadeOutPreviousWords: false,
  },
  "instagram": {
    mode: "instagram",
    wordsPerGroup: 4,
    maxWordsPerLine: 3,
    showPreviousWords: false,
    fadeOutPreviousWords: false,
    useSpringScale: true,
    springDamping: 10,          // ? research: "snappy but not overly bouncy" (TikTok native feel)
    springMass: 0.5,            // ? research: CrePal blog, confirmed working
  },
  "hormozi": {
    mode: "hormozi",
    wordsPerGroup: 3,
    maxWordsPerLine: 2,
    showPreviousWords: false,
    fadeOutPreviousWords: false,
    useSpringScale: true,
    springDamping: 8,           // ? research: "fast pop, minimal bounce" (Hormozi punch)
    springMass: 0.3,            // ? research: spring parameter table from investigation
  },
};

// Enhanced CaptionStyles for full customization
export type HighlightEffect = "none" | "glow" | "box" | "underline" | "pop";
export type HighlightAnimation = "none" | "bounce" | "pulse" | "scale";

export interface CaptionHighlightStyle {
  color: string;
  backgroundColor: string;
  scale: number;  // 1.0 - 1.3
  fontWeight?: number;
  textShadow?: string;
  padding?: string;
  borderRadius?: string;
  effect: HighlightEffect;
  animation: HighlightAnimation;
}

export interface CaptionStyles {
  // Typography (matches text overlay pattern)
  fontFamily: string;  // font-sans, font-serif, font-mono, etc.
  fontSize: string;
  fontWeight: number | string;
  color: string;
  textAlign: "left" | "center" | "right";
  lineHeight: number;
  letterSpacing?: string;
  textShadow?: string;
  
  // Background
  backgroundColor?: string;
  background?: string;
  backdropFilter?: string;
  padding?: string;
  borderRadius?: string;
  
  // Word highlight (when active)
  highlight: CaptionHighlightStyle;
  
  // Legacy compat (deprecated, use highlight)
  highlightStyle?: CaptionHighlightStyle;

  // -- Registry-driven atoms (optional; applied by caption-layer-content). See caption-preset-registry.ts. --
  /** Letter casing for the whole caption (CSS text-transform). */
  textTransform?: "uppercase" | "lowercase" | "capitalize" | "none";
  /** Text outline (CSS -webkit-text-stroke) � the MrBeast look. */
  stroke?: { widthPx: number; color: string };
  /** Per-emphasis-role overrides (keyword/statistic/cta/entity) � coloured-bold per word. */
  roles?: Partial<Record<"keyword" | "statistic" | "cta" | "entity", { color?: string; fontWeight?: number; scale?: number }>>;
}

export interface CaptionOverlay extends BaseOverlay {
  type: OverlayType.CAPTION;
  captions: Caption[];
  styles: CaptionStyles;
  template?: string;
  position?: "bottom" | "top" | "center" | "custom";
  /** Display configuration for word grouping and display mode */
  displayConfig?: CaptionDisplayConfig;
  /** ID of the video overlay this caption is synced to */
  sourceVideoId?: number;
}

export type StickerCategory =
  | "Shapes"
  | "Discounts"
  | "Emojis"
  | "Reviews"
  | "Default";

// Sticker overlay specific
export type StickerOverlay = BaseOverlay & {
  type: OverlayType.STICKER;
  content: string;
  category: StickerCategory;
  styles: BaseStyles & {
    fill?: string;
    stroke?: string;
    strokeWidth?: number;
    scale?: number;
    filter?: string;
    animation?: AnimationConfig;
  };
};

// ============================================================================
// HTML GENERATION METADATA
// ============================================================================

/**
 * Metadata for AI-generated HTML content (scenes, stickers, fancy captions).
 * Used by LLM to maintain visual consistency across generated elements.
 */
export interface HtmlGenerationMetadata {
  /** Font families used in the generated HTML */
  fonts: string[];
  /** Color values used (hex, rgb, rgba) */
  colors: string[];
  /** Background color (or 'transparent') */
  backgroundColor: string;
  /** When this was generated */
  generatedAt: Date;
  /** Type of generation */
  sourceType: 'scene' | 'sticker' | 'fancy-caption';
  /** Number of words (for fancy captions) */
  wordCount?: number;
}

export interface FancyCaptionConfig {
  style: 'bento' | 'scattered' | 'minimal' | 'static' | 'kinetic';
  intensity?: 'low' | 'medium' | 'high';
  segmentStartOffsetFrames: number;
  segmentDurationFrames: number;
  maxWords: number;
  primaryColor?: string;
  accentColor?: string;
  backgroundColor?: string;
  lockTypography?: boolean;
  typographyProfile?: {
    fontPair?: string;
    strokeStyle?: string;
    shadowStyle?: string;
    paletteHint?: string;
  };
}

// HTML Scene overlay specific (full-screen backgrounds, diagrams)
export type HtmlSceneOverlay = BaseOverlay & {
  type: OverlayType.HTML_SCENE;
  content: string; // The generated HTML content
  prompt?: string; // The prompt used to generate this
  /** Extracted style metadata for LLM consistency */
  metadata?: HtmlGenerationMetadata;
  /** Optional source video link for sync/refresh workflows */
  sourceVideoId?: number;
  /** Fancy caption generation config (only when metadata.sourceType === 'fancy-caption') */
  fancyCaptionConfig?: FancyCaptionConfig;
  styles: BaseStyles & {
    backgroundColor?: string;
    borderRadius?: string;
    boxShadow?: string;
    border?: string;
    animation?: AnimationConfig;
  };
};

export type GeneratedSceneFamily =
  | "hook"
  | "problem"
  | "promise"
  | "workflow_demo"
  | "feature_demo"
  | "ui_proof"
  | "proof_metric"
  | "comparison"
  | "social_proof"
  | "objection_handling"
  | "cta"
  | "logo_outro"
  | "section_header";

export type GeneratedSceneVisualArchetype =
  | "TYPE_ONLY"
  | "TYPE_OVER_MEDIA"
  | "UI_FULL_BLEED"
  | "UI_FRAMED"
  | "UI_CROP_ZOOM"
  | "CURSOR_HERO"
  | "UI_FLOAT_STACK"
  | "DEVICE_CONTEXT"
  | "HUMAN_FRAME"
  | "BENTO_GRID"
  | "DIAGRAM_SCHEMATIC"
  | "DATA_VIZ"
  | "SPLIT_COMPARE"
  | "ICON_CONSTELLATION"
  | "LOGO_FIELD";

export type GeneratedSceneFamilyPlan = {
  family: GeneratedSceneFamily;
  evidenceSource: "brand_vault" | "script" | "product_url" | "reference_video" | "default_reference_video" | "structure_doctrine" | "scene_descriptor" | "director_contract";
  sourcePaths: string[];
  visualGoal: string;
  productUiState: string;
  motionIntent: string;
  copyRole: string;
  claimMode: "evidence_backed" | "claim_locked" | "synthetic_demo_only";
  visualArchetype?: GeneratedSceneVisualArchetype;
  evidenceStatus?: "satisfied" | "substituted" | "degraded" | "disabled";
  evidenceDuty?: string[];
  admissibleClaimIds?: string[];
  productAssetUse?: {
    logo: boolean;
    productImage: boolean;
    productUrl: boolean;
  };
  directorStructureId?: string;
  directorBeatIndex?: number;
  sourceFamilyExpression?: string;
};
export type GeneratedSceneElement = {
  id: string;
  role: "headline" | "app-shell" | "panel" | "metric" | "caption" | "cta" | "logo-mark";
  text?: string;
  label?: string;
  value?: string;
  items?: string[];
  emphasis?: "primary" | "accent" | "muted";
};

export type GeneratedSceneAsset = {
  kind: string;
  label: string;
  url: string;
  stored: boolean;
  signalPath?: string;
  sourceType?: string;
};

export type GeneratedSceneOverlay = BaseOverlay & {
  type: OverlayType.GENERATED_SCENE;
  content: string;
  sceneModel: {
    schemaVersion: "saas-generated-scene/v1";
    sceneId: string;
    sceneIndex: number;
    title: string;
    productName: string;
    brand: {
      name: string;
      primaryColor: string;
      accentColor: string;
      backgroundColor: string;
      surfaceColor: string;
      textColor: string;
      mutedTextColor: string;
      fontFamily: string;
    };
    style: {
      category: "saas_product_demo";
      pacing: string;
      uiTreatment: string;
      motion: string;
    };
    familyPlan?: GeneratedSceneFamilyPlan;
    assets?: {
      logos: GeneratedSceneAsset[];
      productImages: GeneratedSceneAsset[];
      productUrl?: string;
      sourcePaths: string[];
    };
    voiceover: {
      script: string;
      status: "pending_tts" | "ready";
      audioUrl?: string;
      assetId?: string;
    } | null;
    elements: GeneratedSceneElement[];
    captionTracks: Array<{
      id: string;
      text: string;
      startMs: number;
      endMs: number;
    }>;
    qualityGates: {
      promptLeakChecked: true;
      brandTokensApplied: boolean;
      readableUiProof: true;
      productSpecificVisualProof?: boolean;
      motionChoreographyPlanned?: boolean;
      finalVisualProof?: boolean;
    };
  };
  sourceMap: Record<string, unknown>;
  styles: BaseStyles;
  metadata?: {
    sourceType: string;
    sceneIndex: number;
    generatedSceneId: string;
    schemaVersion: string;
    directorStructureId?: string;
    directorBeatIndex?: number;
    validation?: { ok: boolean; issues: string[] };
  };
};

// Generated Scene Overlay (SaaS/product renderer contract)

// --- Motion Graphic Overlay (Structure � Theme system) -------------
// React-rendered overlay driven by resolved visual tokens from the
// signal-based Visual Identity Engine. Coexists with HTML_SCENE
// (Shadow DOM) for backward compatibility with existing templates.
export type MotionGraphicOverlay = BaseOverlay & {
  type: OverlayType.MOTION_GRAPHIC;
  structureType: string;
  content: Record<string, string>;
  resolvedTokens: Record<string, any>;
  signalCurves?: Record<string, number[]>;
  contentSignals?: {
    formality: number;
    enthusiasm: number;
    warmth: number;
    emotional_arousal: number;
    pacing_velocity: number;
    humor: number;
    visceral_impact: number;
    visual_dependency: number;
  };
  styles: BaseStyles & {
    backgroundColor?: string;
  };
  metadata?: {
    sourceType: string;
    graphicType: string;
    edlSource?: string;
    edlReason?: string;
  };
};

/** Runtime-only playback descriptor hydrated from a sequence MediaAsset. */
export type MgSequencePlayback = {
  sequenceId: string;
  frameCount: number;
  fps: number;
  width: number;
  height: number;
  transparent: true;
  frameFormat: 'webp';
  cdnBaseUrl: string;
};

/** Full-frame, content-placed MG codegen output. Only assetId is persisted as its sequence FK. */
export type MgSequenceOverlay = BaseOverlay & {
  type: OverlayType.MG_SEQUENCE;
  assetId: string;
  sequence?: MgSequencePlayback;
  styles: BaseStyles;
};
// --- Transition Overlay --------------------------------------------
// A visible tile on the timeline between two clips.
// The tile IS the visual effect (DaVinci model) � it renders both adjacent
// clips internally and composites them using CSS.
//
// CANONICAL TYPE LIST � all other systems (continuity-service, director,
// tools.ts, SFX placer, EDL executor) should reference this type.
// Updated 2026-05-15: consolidated from 3 inconsistent type systems.

export type TransitionStyle =
  // Blend transitions (clips crossfade/overlay)
  | 'dissolve' | 'soft-cut' | 'blur-transition'
  // Color transitions (fade through solid color)
  | 'dip-to-black' | 'dip-to-white' | 'flash'
  // Wipe transitions (clip-path reveal)
  | 'wipe-left' | 'wipe-right' | 'wipe-up' | 'wipe-down' | 'iris-wipe'
  // Motion transitions (transform-based)
  | 'zoom-punch' | 'whip-pan' | 'slide-up' | 'slide-down'
  // Stylistic transitions (special effects)
  | 'glitch' | 'film-burn'
  // Editorial cuts (no visual overlay � the cut IS the transition)
  | 'hard-cut' | 'smash-cut' | 'match-cut' | 'jump-cut' | 'cut-on-action';

export type TransitionOverlay = BaseOverlay & {
  type: OverlayType.TRANSITION;
  /** Transition visual style */
  transitionStyle: TransitionStyle;
  /** ID of the clip BEFORE this transition (scene A) */
  clipAId: number;
  /** ID of the clip AFTER this transition (scene B) */
  clipBId: number;
  /** Easing for the transition blend */
  easing: 'linear' | 'ease-in' | 'ease-out' | 'ease-in-out';
  content: string; // Display name for timeline
  styles: BaseStyles;
};

// HTML Sticker overlay specific (transparent animated elements)
export type HtmlStickerOverlay = BaseOverlay & {
  type: OverlayType.HTML_STICKER;
  content: string; // The generated HTML content
  prompt?: string; // The prompt used to generate this
  /** Extracted style metadata for LLM consistency */
  metadata?: HtmlGenerationMetadata;
  styles: BaseStyles & {
    animation?: AnimationConfig;
  };
};


export interface TemplateCreator {
  id: string;
  name: string;
}

export interface TemplateOverlay {
  id: string;
  name: string;
  description: string;
  createdAt: string;
  updatedAt: string;
  createdBy: TemplateCreator;
  category: string;
  tags: string[];
  thumbnail?: string;
  duration: number;
  aspectRatio?: AspectRatio;
  overlays: Overlay[];
}

export type Overlay =
  | TextOverlay
  | ImageOverlay
  | ShapeOverlay
  | ClipOverlay
  | SoundOverlay
  | CaptionOverlay
  | StickerOverlay
  | HtmlSceneOverlay
  | GeneratedSceneOverlay
  | HtmlStickerOverlay
  | TransitionOverlay
  | MotionGraphicOverlay
  | MgSequenceOverlay;

export type MainProps = {
  readonly overlays: Overlay[];
  readonly setSelectedOverlay: React.Dispatch<
    React.SetStateAction<number | null>
  >;
  readonly selectedOverlay: number | null;
  readonly changeOverlay: (
    overlayId: number,
    updater: (overlay: Overlay) => Overlay
  ) => void;
};

import { z } from "zod";

// Base interface for all timeline items
interface TimelineItem {
  id: string;
  start: number;
  duration: number;
  row: number;
}

// Clip specific properties
export interface Video extends TimelineItem {
  type: OverlayType.VIDEO;
  src: string;
  videoStartTime?: number;
}

// Sound specific properties
export interface Sound extends TimelineItem {
  type: OverlayType.SOUND;
  file: string;
  content: string;
  startFromSound: number;
}

// Base interface for layers
interface Layer extends TimelineItem {
  position: { x: number; y: number };
}

// Text layer specific properties
export interface TextLayer extends Layer {
  type: OverlayType.TEXT;
  text: string;
  fontSize: number;
  fontColor: string;
  fontFamily: string;
  backgroundColor: string;
}

// Shape layer specific properties
export interface ShapeLayer extends Layer {
  type: OverlayType.SHAPE;
  shapeType: "rectangle" | "circle" | "triangle";
  color: string;
  size: { width: number; height: number };
}

// Image layer specific properties
export interface ImageLayer extends Layer {
  type: OverlayType.IMAGE;
  src: string;
  size: { width: number; height: number };
}

// Union type for all possible layers
export type LayerItem = TextLayer | ShapeLayer | ImageLayer;

// Union type for all timeline items
export type TimelineItemUnion = Video | Sound | LayerItem;

// Type for the selected item in the editor
export type SelectedItem = TimelineItemUnion | null;

// Zod schema for composition props

export const CompositionProps = z.object({
  overlays: z.array(z.any()), // Replace with your actual Overlay type
  durationInFrames: z.number(),
  width: z.number(),
  height: z.number(),
  fps: z.number(),
  src: z.string(),
});

// Other types remain the same
export const RenderRequest = z.object({
  id: z.string(),
  inputProps: CompositionProps,
});

export const ProgressRequest = z.object({
  bucketName: z.string(),
  id: z.string(),
});

export type ProgressResponse =
  | { type: "error"; message: string }
  | { type: "progress"; progress: number }
  | { type: "done"; url: string; size: number };

// Additional types
export interface PexelsMedia {
  id: string;
  duration?: number;
  image?: string;
  video_files?: { link: string }[];
}

export interface PexelsAudio {
  id: string;
  title: string;
  artist: string;
  audio_url: string;
  duration: number;
}

export interface LocalSound {
  id: string;
  title: string;
  artist: string;
  file: string;
  duration: number;
}

export type LocalClip = {
  id: string;
  title: string;
  thumbnail: string;
  duration: number;
  videoUrl: string;
};

export type AspectRatio = "16:9" | "1:1" | "4:5" | "9:16";

export interface TimelineRow {
  id: number;
  index: number;
}

export interface WaveformData {
  peaks: number[];
  length: number;
}

// Update EditorContextType
export interface EditorContextType {
  // ... existing context properties ...
  rows: TimelineRow[];
  addRow: () => void;
}

// Update ImageStyles interface to match ClipOverlay style pattern
/**
 * ImageStyles interface defining all the style properties available for image overlays
 *
 * @property filter - CSS filter string applying visual effects (can use presets or custom values)
 * @property borderRadius - Border radius for rounded corners
 * @property objectFit - How the image should be resized/positioned within its container
 * @property objectPosition - Positioning of the image within its container
 * @property boxShadow - CSS box-shadow property for drop shadows
 * @property border - CSS border property for image borders
 * @property animation - Enter/exit animation configuration
 */
export interface ImageStyles extends BaseStyles {
  filter?: string;
  borderRadius?: string;
  objectFit?: "contain" | "cover" | "fill" | "none" | "scale-down";
  objectPosition?: string;
  boxShadow?: string;
  border?: string;
  padding?: string;
  paddingBackgroundColor?: string;
  animation?: AnimationConfig;
}

// Update ImageOverlay to match ClipOverlay pattern
export interface ImageOverlay extends BaseOverlay {
  type: OverlayType.IMAGE;
  src?: string; // Optional - resolved from assetId
  assetId?: string; // Reference to mediaAsset
  content?: string; // Optional thumbnail/preview
  styles: ImageStyles;
}

// Local media file interface
export interface LocalMediaFile {
  id: string;
  name: string;
  type: "video" | "image" | "audio";
  path: string; // Signed URL for display
  assetId?: string; // Asset ID for storage (GCS reference)
  size: number;
  lastModified: number;
  thumbnail?: string;
  duration?: number;
  dimensions?: { width: number; height: number };
  analysisStatus?: string;
}
