export const keywords = [
  "automated content production platform",
  "AI content production platform",
  "content production automation",
  "content production workflow",
  "AI content workflow",
  "marketing content production platform",
  "business content production software",
  "content production platform for agencies",
  "AI content workflow for in-house teams",
  "enterprise content production platform",
  "creator house content production",
  "filmmaker content workflow",
  "brand-consistent content",
  "on-brand content production",
  "AI-assisted content editing",
  "automated video editing",
  "AI video editor",
  "AI thumbnail generator",
  "AI script writer",
  "AI publishing workflow",
  "content performance analysis",
  "content planning software for teams",
  "public profile for content teams",
  "content production platform for filmmakers",
];
