export const keywords = [
  "automated content production platform",
  "AI content production platform",
  "content production automation",
  "AI video production platform",
  "AI video editor",
  "AI video editing software",
  "AI script writer",
  "AI video script generator",
  "AI thumbnail generator",
  "AI thumbnail maker",
  "AI content workflow",
  "brand consistent content",
  "on brand video production",
  "content production platform for agencies",
  "AI content workflow for in-house teams",
  "business content production software",
  "enterprise content production platform",
  "creator house content production",
  "filmmaker content workflow",
  "AI publishing workflow",
  "content performance analysis",
  "automated video editing",
  "AI assisted video editing",
  "content planning software",
  "marketing content production platform",
];
