/**
 * Version Tree - Source of truth for version identity
 * 
 * CRITICAL: This is the ONLY place where version IDs are generated.
 * The graph may only reference nodes that exist in this tree.
 * 
 * Think of it as:
 * - Tree = existence (versions live here)
 * - Graph = meaning (relationships between versions)
 */

export interface VersionMetadata {
  description?: string;
  author?: string;
  tags?: string[];
  isAutoSave?: boolean;
  isMergeResult?: boolean;
  mergedFrom?: string[];
  [key: string]: any;
}

export interface VersionNode {
  versionId: string;
  version: number;
  scriptId: string;
  parentVersionId: string | null;
  childrenVersionIds: string[];
  contentBlockRefs: string[];
  hash: string;
  metadata: VersionMetadata;
  createdAt: Date;
}

/**
 * Generate a unique version ID
 */
function generateVersionId(): string {
  return `v_${Date.now().toString(36)}_${Math.random().toString(36).substr(2, 9)}`;
}

/**
 * Generate hash for content block refs
 */
function hashContentBlockRefs(refs: string[]): string {
  const str = refs.sort().join('|');
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash;
  }
  return `vh_${Math.abs(hash).toString(16)}`;
}

/**
 * Version Tree - Tree data structure for version hierarchy
 * 
 * This is the source of truth for version identity.
 * All version IDs must be generated by this tree.
 */
export class VersionTree {
  private nodes: Map<string, VersionNode> = new Map();
  private rootVersionId: string | null = null;
  private scriptId: string;
  private nextVersion: number = 0;

  constructor(scriptId: string) {
    this.scriptId = scriptId;
  }

  /**
   * Generate a new version ID (only this class can do this)
   */
  generateVersionId(): string {
    return generateVersionId();
  }

  /**
   * Add a new version to the tree
   * Returns the created node with a generated ID
   */
  addVersion(
    parentVersionId: string | null,
    contentBlockRefs: string[],
    metadata: VersionMetadata = {}
  ): VersionNode {
    // Validate parent exists if provided
    if (parentVersionId !== null && !this.nodes.has(parentVersionId)) {
      throw new Error(`Parent version ${parentVersionId} does not exist in tree`);
    }

    // Generate ID (only tree can do this)
    const versionId = this.generateVersionId();
    const version = this.nextVersion++;
    const hash = hashContentBlockRefs(contentBlockRefs);

    const node: VersionNode = {
      versionId,
      version,
      scriptId: this.scriptId,
      parentVersionId,
      childrenVersionIds: [],
      contentBlockRefs: [...contentBlockRefs],
      hash,
      metadata,
      createdAt: new Date(),
    };

    // Add to tree
    this.nodes.set(versionId, node);

    // Update parent's children list
    if (parentVersionId !== null) {
      const parent = this.nodes.get(parentVersionId);
      if (parent) {
        parent.childrenVersionIds.push(versionId);
      }
    } else {
      // This is a root node
      if (this.rootVersionId === null) {
        this.rootVersionId = versionId;
      }
    }

    return { ...node };
  }

  /**
   * Get a version by ID
   */
  getVersion(versionId: string): VersionNode | null {
    const node = this.nodes.get(versionId);
    return node ? { ...node } : null;
  }

  /**
   * Check if a version exists in the tree
   */
  hasVersion(versionId: string): boolean {
    return this.nodes.has(versionId);
  }

  /**
   * Get children of a version
   */
  getChildren(versionId: string): VersionNode[] {
    const node = this.nodes.get(versionId);
    if (!node) return [];
    
    return node.childrenVersionIds
      .map(id => this.nodes.get(id))
      .filter(Boolean) as VersionNode[];
  }

  /**
   * Get ancestors of a version (path to root)
   */
  getAncestors(versionId: string): VersionNode[] {
    const ancestors: VersionNode[] = [];
    let currentId: string | null = versionId;
    
    while (currentId !== null) {
      const node = this.nodes.get(currentId);
      if (!node) break;
      
      if (node.parentVersionId !== null) {
        const parent = this.nodes.get(node.parentVersionId);
        if (parent) {
          ancestors.push({ ...parent });
        }
      }
      currentId = node.parentVersionId;
    }
    
    return ancestors;
  }

  /**
   * Get descendants of a version (all children recursively)
   */
  getDescendants(versionId: string): VersionNode[] {
    const descendants: VersionNode[] = [];
    const queue = [versionId];
    
    while (queue.length > 0) {
      const currentId = queue.shift()!;
      const node = this.nodes.get(currentId);
      if (!node) continue;
      
      for (const childId of node.childrenVersionIds) {
        const child = this.nodes.get(childId);
        if (child) {
          descendants.push({ ...child });
          queue.push(childId);
        }
      }
    }
    
    return descendants;
  }

  /**
   * Get path from root to a version
   */
  getBranchPath(versionId: string): VersionNode[] {
    const path: VersionNode[] = [];
    let currentId: string | null = versionId;
    
    while (currentId !== null) {
      const node = this.nodes.get(currentId);
      if (!node) break;
      path.unshift({ ...node }); // Add to front
      currentId = node.parentVersionId;
    }
    
    return path;
  }

  /**
   * Get timeline slice between two versions
   */
  getTimelineSlice(fromVersionId: string, toVersionId: string): VersionNode[] {
    const fromPath = this.getBranchPath(fromVersionId);
    const toPath = this.getBranchPath(toVersionId);
    
    // Find common ancestor
    const fromIds = new Set(fromPath.map(n => n.versionId));
    let commonIndex = -1;
    for (let i = 0; i < toPath.length; i++) {
      if (fromIds.has(toPath[i].versionId)) {
        commonIndex = i;
        break;
      }
    }
    
    if (commonIndex === -1) {
      // No common ancestor, return both paths
      return [...fromPath, ...toPath];
    }
    
    // Return slice from common ancestor
    return toPath.slice(commonIndex);
  }

  /**
   * Find Lowest Common Ancestor (LCA) of two versions
   * This is foundational - everything else depends on it
   */
  findCommonAncestor(versionId1: string, versionId2: string): VersionNode | null {
    // Get ancestors of both versions
    const ancestors1 = new Set<string>();
    let current: string | null = versionId1;
    
    while (current !== null) {
      ancestors1.add(current);
      const node = this.nodes.get(current);
      current = node?.parentVersionId ?? null;
    }
    
    // Find first common ancestor
    current = versionId2;
    while (current !== null) {
      if (ancestors1.has(current)) {
        return this.getVersion(current);
      }
      const node = this.nodes.get(current);
      current = node?.parentVersionId ?? null;
    }
    
    return null;
  }

  /**
   * Get root version
   */
  getRoot(): VersionNode | null {
    if (!this.rootVersionId) return null;
    return this.getVersion(this.rootVersionId);
  }

  /**
   * Get all versions
   */
  getAllVersions(): VersionNode[] {
    return Array.from(this.nodes.values()).map(n => ({ ...n }));
  }

  /**
   * Get latest version (highest version number)
   */
  getLatestVersion(): VersionNode | null {
    let latest: VersionNode | null = null;
    for (const node of this.nodes.values()) {
      if (!latest || node.version > latest.version) {
        latest = node;
      }
    }
    return latest ? { ...latest } : null;
  }

  /**
   * Validate tree integrity
   */
  validateTree(): { valid: boolean; errors: string[] } {
    const errors: string[] = [];
    
    for (const [id, node] of this.nodes) {
      // Check parent reference
      if (node.parentVersionId !== null && !this.nodes.has(node.parentVersionId)) {
        errors.push(`Node ${id} references non-existent parent ${node.parentVersionId}`);
      }
      
      // Check children references
      for (const childId of node.childrenVersionIds) {
        if (!this.nodes.has(childId)) {
          errors.push(`Node ${id} references non-existent child ${childId}`);
        }
      }
    }
    
    return {
      valid: errors.length === 0,
      errors,
    };
  }

  /**
   * Serialize tree to JSON for persistence
   */
  toJSON(): {
    scriptId: string;
    rootVersionId: string | null;
    nextVersion: number;
    nodes: VersionNode[];
  } {
    return {
      scriptId: this.scriptId,
      rootVersionId: this.rootVersionId,
      nextVersion: this.nextVersion,
      nodes: Array.from(this.nodes.values()),
    };
  }

  /**
   * Load tree from JSON
   */
  static fromJSON(data: {
    scriptId: string;
    rootVersionId: string | null;
    nextVersion: number;
    nodes: VersionNode[];
  }): VersionTree {
    const tree = new VersionTree(data.scriptId);
    tree.rootVersionId = data.rootVersionId;
    tree.nextVersion = data.nextVersion;
    
    for (const node of data.nodes) {
      tree.nodes.set(node.versionId, {
        ...node,
        createdAt: new Date(node.createdAt),
      });
    }
    
    return tree;
  }
}

export default VersionTree;
