import { z } from 'zod';

import {
  CAP2_CURRENT_TRUTH_REISSUE_AUDIT_V10,
  getCap2CurrentTruthDomainEvidencePathsV10,
  hashNormalizedCap2FileV10,
  hashNormalizedCap2SourceSnapshotV10,
  type Cap2CurrentTruthDomainV10,
} from './cap2-current-truth-reissue-audit-v10';
import {
  CAP2_FROZEN_CATALOG_HASH_V1,
  hashCanonicalCap2ArtifactV1,
} from './cap2-current-truth-freeze-v1';

const SHA256 = z.string().regex(/^[a-f0-9]{64}$/);
const PRIOR_MANIFEST_SHA256 = '6257cb82bda973f0fb33d1a51b31d37d77af9c6ada9a72cf3f187feed58f80dd';
const PRIOR_SOURCE_SNAPSHOT_SHA256 = '2cfb53bb39458f3c18c1f4cd79d4ca78a16a2bf3901ec51bca7b5907534f7290';
const SOURCE_SNAPSHOT_SHA256 = '597f43a3c9faf7ccd33adfdf7de87fe13efdca99facded3737447c20439b2cdd';
const CURRENT_COMMIT_V11 = '1ada3fa6108bf595a4d62861cbf57ff716ae8d8e';

export const CAP2_CURRENT_TRUTH_SOURCE_OBSERVATIONS_V11 = deepFreeze(
[
  {
    "sourceId": "api.editron-linked-route-exports",
    "category": "API_ROUTE",
    "authorityClaim": "NO_AUTHORITY_CLAIM",
    "extraction": {
      "kind": "ROUTE_EXPORT_SCAN",
      "pattern": "app/api/services/editron/** plus route modules importing @/lib/editron",
      "roots": [
        "app/api"
      ]
    },
    "observedCount": 196,
    "observedIds": [
      "DELETE /api/dashboard/attention",
      "DELETE /api/services/editron/brands/[brandId]",
      "DELETE /api/services/editron/chat/sessions/[sessionId]/delete",
      "DELETE /api/services/editron/media/delete",
      "DELETE /api/services/editron/media/timestamp-preview/session",
      "DELETE /api/services/editron/projects/[projectId]",
      "DELETE /api/services/uploaderx/videos",
      "GET /api/admin/brand-intelligence/status",
      "GET /api/admin/projects/status-board",
      "GET /api/admin/services/usage",
      "GET /api/cron/check-task-timeouts",
      "GET /api/cron/cleanup-stale-uploads",
      "GET /api/cron/recover-chat-render-verifications",
      "GET /api/cron/recover-media-proxy-master-transcode",
      "GET /api/cron/recover-media-source-audio",
      "GET /api/cron/recover-media-source-audio-evidence-backfill",
      "GET /api/cron/recover-media-source-pts-cadence-v3",
      "GET /api/cron/recover-media-source-pts-cadence-version-evidence-backfill",
      "GET /api/cron/recover-stuck-projects",
      "GET /api/cron/sweep-chat-reference-style-jobs",
      "GET /api/cron/sweep-mg-render-jobs",
      "GET /api/dashboard/attention",
      "GET /api/health",
      "GET /api/internal/thinkforge/canary-attestation",
      "GET /api/org/[orgId]/projects",
      "GET /api/services/editron",
      "GET /api/services/editron/analysis",
      "GET /api/services/editron/assets/url/[assetId]",
      "GET /api/services/editron/brands",
      "GET /api/services/editron/brands/[brandId]",
      "GET /api/services/editron/build-info",
      "GET /api/services/editron/chat/operation-status",
      "GET /api/services/editron/chat/sessions/[sessionId]/history",
      "GET /api/services/editron/chat/sessions/list",
      "GET /api/services/editron/checkpoints/list",
      "GET /api/services/editron/cloudrun/progress",
      "GET /api/services/editron/history",
      "GET /api/services/editron/lottie",
      "GET /api/services/editron/lottie/search",
      "GET /api/services/editron/media/batches/[uploadBatchId]",
      "GET /api/services/editron/media/list",
      "GET /api/services/editron/media/references",
      "GET /api/services/editron/media/segment",
      "GET /api/services/editron/media/timestamp-preview/[pictureHandle]",
      "GET /api/services/editron/media/timestamp-preview/audio/[projectId]/[audioHandle]",
      "GET /api/services/editron/media/upload/multipart/status",
      "GET /api/services/editron/mg-eval/media",
      "GET /api/services/editron/mg-eval/review",
      "GET /api/services/editron/motion-graphics",
      "GET /api/services/editron/music-catalog/reference-song",
      "GET /api/services/editron/music-catalog/search",
      "GET /api/services/editron/music-discovery/search",
      "GET /api/services/editron/pexels/search",
      "GET /api/services/editron/projects/[projectId]",
      "GET /api/services/editron/projects/list",
      "GET /api/services/editron/render/active",
      "GET /api/services/editron/render/history",
      "GET /api/services/editron/saas-explainer/status/[jobId]",
      "GET /api/services/editron/sfx-library/search",
      "GET /api/services/editron/status/[id]",
      "GET /api/services/editron/style-transfer",
      "GET /api/services/editron/transcribe",
      "GET /api/services/thinkforge/refinery",
      "GET /api/services/uploaderx/videos",
      "PATCH /api/services/editron/brands/[brandId]",
      "PATCH /api/services/editron/chat/sessions/[sessionId]/rename",
      "PATCH /api/services/editron/media/pin",
      "POST /api/avatar-vault/voice-uploads",
      "POST /api/internal/migrate-audio",
      "POST /api/internal/thinkforge/canary-attestation",
      "POST /api/internal/workers/asset-analysis",
      "POST /api/internal/workers/asset-deep-analysis",
      "POST /api/internal/workers/asset-transcription",
      "POST /api/internal/workers/brand-learning",
      "POST /api/internal/workers/chapter-concat",
      "POST /api/internal/workers/chat-deep-analysis",
      "POST /api/internal/workers/chat-dubbing",
      "POST /api/internal/workers/chat-editorial-intent",
      "POST /api/internal/workers/chat-reference-style",
      "POST /api/internal/workers/clickatron/variation",
      "POST /api/internal/workers/director",
      "POST /api/internal/workers/director/failure",
      "POST /api/internal/workers/editorial-plan",
      "POST /api/internal/workers/graph-sync",
      "POST /api/internal/workers/media-proxy-master-transcode",
      "POST /api/internal/workers/media-source-audio-evidence-backfill",
      "POST /api/internal/workers/media-source-audio-materialization",
      "POST /api/internal/workers/media-source-pts-cadence",
      "POST /api/internal/workers/media-source-pts-cadence-v3",
      "POST /api/internal/workers/media-source-pts-cadence-version-evidence-backfill",
      "POST /api/internal/workers/media-source-qualification",
      "POST /api/internal/workers/mg-design",
      "POST /api/internal/workers/mg-render",
      "POST /api/internal/workers/mg-render/storage-authorize",
      "POST /api/internal/workers/native-media-final-render-preparation",
      "POST /api/internal/workers/phase0-rendered-evidence",
      "POST /api/internal/workers/pipeline/audio",
      "POST /api/internal/workers/pipeline/reference-image",
      "POST /api/internal/workers/pipeline/storyboard-image",
      "POST /api/internal/workers/pipeline/video",
      "POST /api/internal/workers/render-finalizer",
      "POST /api/internal/workers/render-finalizer/failure",
      "POST /api/internal/workers/thinkforge/trend-analysis",
      "POST /api/internal/workers/tribe-analysis",
      "POST /api/internal/workers/video-analysis",
      "POST /api/org/[orgId]/projects",
      "POST /api/services/alyzitron/analyze",
      "POST /api/services/alyzitron/processor",
      "POST /api/services/alyzitron/r2/multipart/complete",
      "POST /api/services/alyzitron/r2/multipart/init",
      "POST /api/services/alyzitron/r2/multipart/sign-part",
      "POST /api/services/clickatron/save-sketch-result",
      "POST /api/services/clickatron/session/[id]/commit",
      "POST /api/services/editron",
      "POST /api/services/editron/analysis",
      "POST /api/services/editron/analysis/test-single",
      "POST /api/services/editron/analyze",
      "POST /api/services/editron/assets/cdn-resolve",
      "POST /api/services/editron/assets/create-public",
      "POST /api/services/editron/assets/validate",
      "POST /api/services/editron/audio/analyze-beats",
      "POST /api/services/editron/auto-edit",
      "POST /api/services/editron/auto-edit/cancel",
      "POST /api/services/editron/auto-edit/from-asset",
      "POST /api/services/editron/auto-edit/from-batch",
      "POST /api/services/editron/auto-edit/moment-plan",
      "POST /api/services/editron/auto-edit/rescue",
      "POST /api/services/editron/brands",
      "POST /api/services/editron/chat/attachments",
      "POST /api/services/editron/chat/sessions/create",
      "POST /api/services/editron/chat/stream",
      "POST /api/services/editron/chat/tool-call",
      "POST /api/services/editron/checkpoints/create",
      "POST /api/services/editron/checkpoints/restore",
      "POST /api/services/editron/cloudrun/render",
      "POST /api/services/editron/cloudrun/render/webhook",
      "POST /api/services/editron/debug/simulate-assembly",
      "POST /api/services/editron/director/execute",
      "POST /api/services/editron/freeform",
      "POST /api/services/editron/html-scene/edit",
      "POST /api/services/editron/match-edit/analyze",
      "POST /api/services/editron/match-edit/generate-gap",
      "POST /api/services/editron/media/search",
      "POST /api/services/editron/media/segment",
      "POST /api/services/editron/media/timestamp-preview/session",
      "POST /api/services/editron/media/upload",
      "POST /api/services/editron/media/upload/direct",
      "POST /api/services/editron/media/upload/multipart/complete",
      "POST /api/services/editron/media/upload/multipart/init",
      "POST /api/services/editron/media/upload/multipart/part",
      "POST /api/services/editron/media/upload/multipart/part-url",
      "POST /api/services/editron/media/upload/swap",
      "POST /api/services/editron/media/upload/url",
      "POST /api/services/editron/mg-eval/review",
      "POST /api/services/editron/motion-graphics",
      "POST /api/services/editron/projects/[projectId]/audio-assets/assign",
      "POST /api/services/editron/projects/[projectId]/autosave",
      "POST /api/services/editron/projects/[projectId]/background-music",
      "POST /api/services/editron/projects/[projectId]/music-catalog/ingest",
      "POST /api/services/editron/projects/[projectId]/native-video-audio-rights",
      "POST /api/services/editron/projects/[projectId]/save",
      "POST /api/services/editron/projects/[projectId]/uploaded-export-audio-rights",
      "POST /api/services/editron/projects/create",
      "POST /api/services/editron/projects/import-from-script",
      "POST /api/services/editron/quality-review",
      "POST /api/services/editron/render/finalization/retry",
      "POST /api/services/editron/saas-explainer/chat-edit",
      "POST /api/services/editron/saas-explainer/finalize",
      "POST /api/services/editron/saas-explainer/ingest-doc",
      "POST /api/services/editron/saas-explainer/ingest-reference",
      "POST /api/services/editron/saas-explainer/intake",
      "POST /api/services/editron/saas-explainer/plan",
      "POST /api/services/editron/sfx-library/ingest",
      "POST /api/services/editron/style-transfer",
      "POST /api/services/editron/submit",
      "POST /api/services/editron/transcribe",
      "POST /api/services/editron/transitions/suggest-sfx",
      "POST /api/services/editron/validate-video",
      "POST /api/services/pipeline/reference-images/[refSetId]/subject/[subjectId]/upload",
      "POST /api/services/pipeline/storyboard/[id]/finalize",
      "POST /api/services/pipeline/storyboard/[id]/generate-videos",
      "POST /api/services/pipeline/storyboard/[id]/scene/[sceneIndex]/upload-image",
      "POST /api/services/pipeline/storyboard/generate",
      "POST /api/services/thinkforge/chat",
      "POST /api/services/thinkforge/enhance",
      "POST /api/services/thinkforge/ideas",
      "POST /api/services/thinkforge/refinery",
      "POST /api/services/thinkforge/script/edit",
      "POST /api/services/thinkforge/script/edit-blocks",
      "POST /api/services/thinkforge/script/refresh-production-contract",
      "POST /api/services/thinkforge/sidecar",
      "POST /api/services/thinkforge/trends/analyze",
      "POST /api/services/thinkforge/trends/reference",
      "POST /api/services/thinkforge/url-brief",
      "POST /api/services/uploaderx/videos",
      "PUT /api/services/editron/style-transfer"
    ],
    "evidencePaths": [
      "app/api/admin/brand-intelligence/status/route.ts",
      "app/api/admin/projects/status-board/route.ts",
      "app/api/admin/services/usage/route.ts",
      "app/api/avatar-vault/voice-uploads/route.ts",
      "app/api/cron/check-task-timeouts/route.ts",
      "app/api/cron/cleanup-stale-uploads/route.ts",
      "app/api/cron/recover-chat-render-verifications/route.ts",
      "app/api/cron/recover-media-proxy-master-transcode/route.ts",
      "app/api/cron/recover-media-source-audio-evidence-backfill/route.ts",
      "app/api/cron/recover-media-source-audio/route.ts",
      "app/api/cron/recover-media-source-pts-cadence-v3/route.ts",
      "app/api/cron/recover-media-source-pts-cadence-version-evidence-backfill/route.ts",
      "app/api/cron/recover-stuck-projects/route.ts",
      "app/api/cron/sweep-chat-reference-style-jobs/route.ts",
      "app/api/cron/sweep-mg-render-jobs/route.ts",
      "app/api/dashboard/attention/route.ts",
      "app/api/health/route.ts",
      "app/api/internal/migrate-audio/route.ts",
      "app/api/internal/thinkforge/canary-attestation/route.ts",
      "app/api/internal/workers/asset-analysis/route.ts",
      "app/api/internal/workers/asset-deep-analysis/route.ts",
      "app/api/internal/workers/asset-transcription/route.ts",
      "app/api/internal/workers/brand-learning/route.ts",
      "app/api/internal/workers/chapter-concat/route.ts",
      "app/api/internal/workers/chat-deep-analysis/route.ts",
      "app/api/internal/workers/chat-dubbing/route.ts",
      "app/api/internal/workers/chat-editorial-intent/route.ts",
      "app/api/internal/workers/chat-reference-style/route.ts",
      "app/api/internal/workers/clickatron/variation/route.ts",
      "app/api/internal/workers/director/failure/route.ts",
      "app/api/internal/workers/director/route.ts",
      "app/api/internal/workers/editorial-plan/route.ts",
      "app/api/internal/workers/graph-sync/route.ts",
      "app/api/internal/workers/media-proxy-master-transcode/route.ts",
      "app/api/internal/workers/media-source-audio-evidence-backfill/route.ts",
      "app/api/internal/workers/media-source-audio-materialization/route.ts",
      "app/api/internal/workers/media-source-pts-cadence-v3/route.ts",
      "app/api/internal/workers/media-source-pts-cadence-version-evidence-backfill/route.ts",
      "app/api/internal/workers/media-source-pts-cadence/route.ts",
      "app/api/internal/workers/media-source-qualification/route.ts",
      "app/api/internal/workers/mg-design/route.ts",
      "app/api/internal/workers/mg-render/route.ts",
      "app/api/internal/workers/mg-render/storage-authorize/route.ts",
      "app/api/internal/workers/native-media-final-render-preparation/route.ts",
      "app/api/internal/workers/phase0-rendered-evidence/route.ts",
      "app/api/internal/workers/pipeline/audio/route.ts",
      "app/api/internal/workers/pipeline/reference-image/route.ts",
      "app/api/internal/workers/pipeline/storyboard-image/route.ts",
      "app/api/internal/workers/pipeline/video/route.ts",
      "app/api/internal/workers/render-finalizer/failure/route.ts",
      "app/api/internal/workers/render-finalizer/route.ts",
      "app/api/internal/workers/thinkforge/trend-analysis/route.ts",
      "app/api/internal/workers/tribe-analysis/route.ts",
      "app/api/internal/workers/video-analysis/route.ts",
      "app/api/org/[orgId]/projects/route.ts",
      "app/api/services/alyzitron/analyze/route.ts",
      "app/api/services/alyzitron/processor/route.ts",
      "app/api/services/alyzitron/r2/multipart/complete/route.ts",
      "app/api/services/alyzitron/r2/multipart/init/route.ts",
      "app/api/services/alyzitron/r2/multipart/sign-part/route.ts",
      "app/api/services/clickatron/save-sketch-result/route.ts",
      "app/api/services/clickatron/session/[id]/commit/route.ts",
      "app/api/services/editron/analysis/route.ts",
      "app/api/services/editron/analysis/test-single/route.ts",
      "app/api/services/editron/analyze/route.ts",
      "app/api/services/editron/assets/cdn-resolve/route.ts",
      "app/api/services/editron/assets/create-public/route.ts",
      "app/api/services/editron/assets/url/[assetId]/route.ts",
      "app/api/services/editron/assets/validate/route.ts",
      "app/api/services/editron/audio/analyze-beats/route.ts",
      "app/api/services/editron/auto-edit/cancel/route.ts",
      "app/api/services/editron/auto-edit/from-asset/route.ts",
      "app/api/services/editron/auto-edit/from-batch/route.ts",
      "app/api/services/editron/auto-edit/moment-plan/route.ts",
      "app/api/services/editron/auto-edit/rescue/route.ts",
      "app/api/services/editron/auto-edit/route.ts",
      "app/api/services/editron/brands/[brandId]/route.ts",
      "app/api/services/editron/brands/route.ts",
      "app/api/services/editron/build-info/route.ts",
      "app/api/services/editron/chat/attachments/route.ts",
      "app/api/services/editron/chat/operation-status/route.ts",
      "app/api/services/editron/chat/sessions/[sessionId]/delete/route.ts",
      "app/api/services/editron/chat/sessions/[sessionId]/history/route.ts",
      "app/api/services/editron/chat/sessions/[sessionId]/rename/route.ts",
      "app/api/services/editron/chat/sessions/create/route.ts",
      "app/api/services/editron/chat/sessions/list/route.ts",
      "app/api/services/editron/chat/stream/route.ts",
      "app/api/services/editron/chat/tool-call/route.ts",
      "app/api/services/editron/checkpoints/create/route.ts",
      "app/api/services/editron/checkpoints/list/route.ts",
      "app/api/services/editron/checkpoints/restore/route.ts",
      "app/api/services/editron/cloudrun/progress/route.ts",
      "app/api/services/editron/cloudrun/render/route.ts",
      "app/api/services/editron/cloudrun/render/webhook/route.ts",
      "app/api/services/editron/debug/simulate-assembly/route.ts",
      "app/api/services/editron/director/execute/route.ts",
      "app/api/services/editron/freeform/route.ts",
      "app/api/services/editron/history/route.ts",
      "app/api/services/editron/html-scene/edit/route.ts",
      "app/api/services/editron/lottie/route.ts",
      "app/api/services/editron/lottie/search/route.ts",
      "app/api/services/editron/match-edit/analyze/route.ts",
      "app/api/services/editron/match-edit/generate-gap/route.ts",
      "app/api/services/editron/media/batches/[uploadBatchId]/route.ts",
      "app/api/services/editron/media/delete/route.ts",
      "app/api/services/editron/media/list/route.ts",
      "app/api/services/editron/media/pin/route.ts",
      "app/api/services/editron/media/references/route.ts",
      "app/api/services/editron/media/search/route.ts",
      "app/api/services/editron/media/segment/route.ts",
      "app/api/services/editron/media/timestamp-preview/[pictureHandle]/route.ts",
      "app/api/services/editron/media/timestamp-preview/audio/[projectId]/[audioHandle]/route.ts",
      "app/api/services/editron/media/timestamp-preview/session/route.ts",
      "app/api/services/editron/media/upload/direct/route.ts",
      "app/api/services/editron/media/upload/multipart/complete/route.ts",
      "app/api/services/editron/media/upload/multipart/init/route.ts",
      "app/api/services/editron/media/upload/multipart/part-url/route.ts",
      "app/api/services/editron/media/upload/multipart/part/route.ts",
      "app/api/services/editron/media/upload/multipart/status/route.ts",
      "app/api/services/editron/media/upload/route.ts",
      "app/api/services/editron/media/upload/swap/route.ts",
      "app/api/services/editron/media/upload/url/route.ts",
      "app/api/services/editron/mg-eval/media/route.ts",
      "app/api/services/editron/mg-eval/review/route.ts",
      "app/api/services/editron/motion-graphics/route.ts",
      "app/api/services/editron/music-catalog/reference-song/route.ts",
      "app/api/services/editron/music-catalog/search/route.ts",
      "app/api/services/editron/music-discovery/search/route.ts",
      "app/api/services/editron/pexels/search/route.ts",
      "app/api/services/editron/projects/[projectId]/audio-assets/assign/route.ts",
      "app/api/services/editron/projects/[projectId]/autosave/route.ts",
      "app/api/services/editron/projects/[projectId]/background-music/route.ts",
      "app/api/services/editron/projects/[projectId]/music-catalog/ingest/route.ts",
      "app/api/services/editron/projects/[projectId]/native-video-audio-rights/route.ts",
      "app/api/services/editron/projects/[projectId]/route.ts",
      "app/api/services/editron/projects/[projectId]/save/route.ts",
      "app/api/services/editron/projects/[projectId]/uploaded-export-audio-rights/route.ts",
      "app/api/services/editron/projects/create/route.ts",
      "app/api/services/editron/projects/import-from-script/route.ts",
      "app/api/services/editron/projects/list/route.ts",
      "app/api/services/editron/quality-review/route.ts",
      "app/api/services/editron/render/active/route.ts",
      "app/api/services/editron/render/finalization/retry/route.ts",
      "app/api/services/editron/render/history/route.ts",
      "app/api/services/editron/route.ts",
      "app/api/services/editron/saas-explainer/chat-edit/route.ts",
      "app/api/services/editron/saas-explainer/finalize/route.ts",
      "app/api/services/editron/saas-explainer/ingest-doc/route.ts",
      "app/api/services/editron/saas-explainer/ingest-reference/route.ts",
      "app/api/services/editron/saas-explainer/intake/route.ts",
      "app/api/services/editron/saas-explainer/plan/route.ts",
      "app/api/services/editron/saas-explainer/status/[jobId]/route.ts",
      "app/api/services/editron/sfx-library/ingest/route.ts",
      "app/api/services/editron/sfx-library/search/route.ts",
      "app/api/services/editron/status/[id]/route.ts",
      "app/api/services/editron/style-transfer/route.ts",
      "app/api/services/editron/submit/route.ts",
      "app/api/services/editron/transcribe/route.ts",
      "app/api/services/editron/transitions/suggest-sfx/route.ts",
      "app/api/services/editron/validate-video/route.ts",
      "app/api/services/pipeline/reference-images/[refSetId]/subject/[subjectId]/upload/route.ts",
      "app/api/services/pipeline/storyboard/[id]/finalize/route.ts",
      "app/api/services/pipeline/storyboard/[id]/generate-videos/route.ts",
      "app/api/services/pipeline/storyboard/[id]/scene/[sceneIndex]/upload-image/route.ts",
      "app/api/services/pipeline/storyboard/generate/route.ts",
      "app/api/services/thinkforge/chat/route.ts",
      "app/api/services/thinkforge/enhance/route.ts",
      "app/api/services/thinkforge/ideas/route.ts",
      "app/api/services/thinkforge/refinery/route.ts",
      "app/api/services/thinkforge/script/edit-blocks/route.ts",
      "app/api/services/thinkforge/script/edit/route.ts",
      "app/api/services/thinkforge/script/refresh-production-contract/route.ts",
      "app/api/services/thinkforge/sidecar/route.ts",
      "app/api/services/thinkforge/trends/analyze/route.ts",
      "app/api/services/thinkforge/trends/reference/route.ts",
      "app/api/services/thinkforge/url-brief/route.ts",
      "app/api/services/uploaderx/videos/route.ts"
    ],
    "countingSemantics": "Each METHOD plus route path is one observed HTTP entrypoint.",
    "notes": "Includes cross-product and administrative routes that import Editron code. It is not a count of editing capabilities."
  },
  {
    "sourceId": "chat.compatibility-tool-bundle",
    "category": "CHAT_EXECUTION_BUNDLE",
    "authorityClaim": "NO_AUTHORITY_CLAIM",
    "extraction": {
      "kind": "TS_TOOL_RETURN_BUNDLE",
      "symbol": "createTools plus four family factories",
      "roots": [
        "lib/editron/agent/chat-asset-tools.ts",
        "lib/editron/agent/chat-audio-tools.ts",
        "lib/editron/agent/chat-transcript-tools.ts",
        "lib/editron/agent/chat-visual-tools.ts",
        "lib/editron/agent/tools.ts"
      ]
    },
    "observedCount": 59,
    "observedIds": [
      "add_captions",
      "add_fancy_captions",
      "add_motion_graphic",
      "add_overlay",
      "add_sfx",
      "add_transition",
      "analyze_clip_audio",
      "analyze_clip_video",
      "analyze_video_content",
      "apply_audio_ducking",
      "apply_camera_shake",
      "apply_fade",
      "apply_filter",
      "apply_speed_ramp",
      "apply_style",
      "auto_edit_from_script",
      "auto_motion_graphics",
      "batch_edit_captions",
      "batch_update_overlays",
      "close_gaps",
      "cut_section",
      "delete_overlay",
      "edit_html_scene",
      "extract_style",
      "find_audio_moment",
      "find_transcript_moment",
      "find_visual_moment",
      "generate_html_scene",
      "generate_html_sticker",
      "get_timeline_view",
      "get_video_transcription",
      "inspect_user_asset",
      "list_user_assets",
      "move_retime_overlay",
      "read_project_file",
      "reframe_project",
      "refresh_captions",
      "refresh_fancy_captions",
      "regenerate_bgm",
      "regenerate_scene",
      "reorder_layer",
      "replace_sfx",
      "resolve_audio_edit",
      "resolve_keyframe_edit",
      "resolve_sticker_overlay",
      "resolve_transcript_edit",
      "resolve_user_asset_overlay",
      "resolve_visual_edit",
      "restore_ai_edit_checkpoint",
      "search_stock_footage",
      "search_user_assets",
      "set_keyframes",
      "split_overlay",
      "sync_cuts_to_beats",
      "sync_style",
      "trim_overlay",
      "update_overlay",
      "use_matching_footage",
      "visual_inspect_frame"
    ],
    "evidencePaths": [
      "lib/editron/agent/chat-asset-tools.ts",
      "lib/editron/agent/chat-audio-tools.ts",
      "lib/editron/agent/chat-transcript-tools.ts",
      "lib/editron/agent/chat-visual-tools.ts",
      "lib/editron/agent/tools.ts"
    ],
    "countingSemantics": "Each resolved returned tool name is one bundle entry.",
    "notes": "This is the compatibility bundle before request-time exposure and policy filtering."
  },
  {
    "sourceId": "chat.registry-descriptors",
    "category": "CHAT_DESCRIPTOR",
    "authorityClaim": "NO_AUTHORITY_CLAIM",
    "extraction": {
      "kind": "TS_OBJECT_KEYS",
      "symbol": "CHAT_TOOL_REGISTRY",
      "roots": [
        "lib/editron/agent/chat-tool-registry.ts"
      ]
    },
    "observedCount": 66,
    "observedIds": [
      "add_captions",
      "add_fancy_captions",
      "add_motion_graphic",
      "add_overlay",
      "add_sfx",
      "add_transition",
      "analyze_clip_audio",
      "analyze_clip_video",
      "analyze_video_content",
      "apply_audio_ducking",
      "apply_camera_shake",
      "apply_editorial_intent",
      "apply_fade",
      "apply_filter",
      "apply_reference_style",
      "apply_speed_ramp",
      "apply_style",
      "auto_edit_from_script",
      "auto_motion_graphics",
      "batch_edit_captions",
      "batch_update_overlays",
      "close_gaps",
      "cut_section",
      "delete_overlay",
      "dub_selected_dialogue",
      "edit_html_scene",
      "extract_style",
      "find_audio_moment",
      "find_transcript_moment",
      "find_visual_moment",
      "generate_html_scene",
      "generate_html_sticker",
      "get_clip_analysis_result",
      "get_dubbing_job_result",
      "get_timeline_view",
      "get_video_transcription",
      "inspect_user_asset",
      "list_user_assets",
      "move_retime_overlay",
      "queue_resolved_clip_analysis",
      "read_project_file",
      "reframe_project",
      "refresh_captions",
      "refresh_fancy_captions",
      "regenerate_bgm",
      "regenerate_scene",
      "reorder_layer",
      "replace_sfx",
      "resolve_audio_edit",
      "resolve_clip_analysis",
      "resolve_keyframe_edit",
      "resolve_sticker_overlay",
      "resolve_transcript_edit",
      "resolve_user_asset_overlay",
      "resolve_visual_edit",
      "restore_ai_edit_checkpoint",
      "search_stock_footage",
      "search_user_assets",
      "set_keyframes",
      "split_overlay",
      "sync_cuts_to_beats",
      "sync_style",
      "trim_overlay",
      "update_overlay",
      "use_matching_footage",
      "visual_inspect_frame"
    ],
    "evidencePaths": [
      "lib/editron/agent/chat-tool-registry.ts"
    ],
    "countingSemantics": "Each object property is one central chat metadata descriptor.",
    "notes": "Descriptor presence does not prove runtime inclusion, shared ownership, mutation safety or certification."
  },
  {
    "sourceId": "director.execute-plan-callers",
    "category": "DIRECTOR_JOB",
    "authorityClaim": "NO_AUTHORITY_CLAIM",
    "extraction": {
      "kind": "SYMBOL_TEXT_CALLERS",
      "symbol": "executeDirectorPlan",
      "roots": [
        "app/api",
        "lib/editron"
      ]
    },
    "observedCount": 10,
    "observedIds": [
      "app/api/internal/workers/director/route.ts",
      "app/api/internal/workers/tribe-analysis/route.ts",
      "app/api/internal/workers/video-analysis/route.ts",
      "app/api/services/editron/auto-edit/from-asset/route.ts",
      "app/api/services/editron/auto-edit/from-batch/route.ts",
      "app/api/services/editron/director/execute/route.ts",
      "lib/editron/agent/director-agent.ts",
      "lib/editron/services/assist-lane.ts",
      "lib/editron/services/chat-editorial-intent-job.ts",
      "lib/editron/services/chat-reference-style-job.ts"
    ],
    "evidencePaths": [
      "app/api/internal/workers/director/route.ts",
      "app/api/internal/workers/tribe-analysis/route.ts",
      "app/api/internal/workers/video-analysis/route.ts",
      "app/api/services/editron/auto-edit/from-asset/route.ts",
      "app/api/services/editron/auto-edit/from-batch/route.ts",
      "app/api/services/editron/director/execute/route.ts",
      "lib/editron/agent/director-agent.ts",
      "lib/editron/services/assist-lane.ts",
      "lib/editron/services/chat-editorial-intent-job.ts",
      "lib/editron/services/chat-reference-style-job.ts"
    ],
    "countingSemantics": "Each non-research source file containing executeDirectorPlan is one observed caller/definition surface.",
    "notes": "The list includes the defining module and callers; Phase 3 must distinguish them and trace actual control flow."
  },
  {
    "sourceId": "manual.editor-context-functions",
    "category": "MANUAL_UI",
    "authorityClaim": "NO_AUTHORITY_CLAIM",
    "extraction": {
      "kind": "TS_INTERFACE_FUNCTION_MEMBERS",
      "symbol": "EditorContextProps",
      "roots": [
        "components/editron/editor/version-7.0.0/contexts/editor-context.tsx"
      ]
    },
    "observedCount": 27,
    "observedIds": [
      "addOverlay",
      "cancelRender",
      "changeOverlay",
      "deleteOverlay",
      "deleteOverlaysByRow",
      "duplicateOverlay",
      "formatTime",
      "getAspectRatioDimensions",
      "getProjectState",
      "handleOverlayChange",
      "handleTimelineClick",
      "loadState",
      "redo",
      "renderMedia",
      "resetOverlays",
      "saveProject",
      "seekTo",
      "setAspectRatio",
      "setIsAIProcessing",
      "setMarkers",
      "setOverlays",
      "setPlaybackRate",
      "splitOverlay",
      "togglePlayPause",
      "undo",
      "updateOverlayStyles",
      "updatePlayerDimensions"
    ],
    "evidencePaths": [
      "components/editron/editor/version-7.0.0/contexts/editor-context.tsx"
    ],
    "countingSemantics": "Each function-typed EditorContextProps member is one observed manual/client operation surface.",
    "notes": "The interface mixes editing, playback, rendering, persistence and UI state; rows are not yet atomic capabilities."
  },
  {
    "sourceId": "manual.timeline-shortcuts",
    "category": "SHORTCUT",
    "authorityClaim": "NO_AUTHORITY_CLAIM",
    "extraction": {
      "kind": "TS_CALL_STRING_ARGUMENTS",
      "symbol": "useHotkeys",
      "roots": [
        "components/editron/editor/version-7.0.0/hooks/use-timeline-shortcuts.ts"
      ]
    },
    "observedCount": 9,
    "observedIds": [
      "alt+-, alt+minus",
      "alt+=, alt+plus",
      "alt+space",
      "d, ctrl+d",
      "meta+c, ctrl+c",
      "meta+shift+z, ctrl+shift+z, meta+y, ctrl+y",
      "meta+v, ctrl+v",
      "meta+z, ctrl+z",
      "s"
    ],
    "evidencePaths": [
      "components/editron/editor/version-7.0.0/hooks/use-timeline-shortcuts.ts"
    ],
    "countingSemantics": "Each useHotkeys binding string is one observed shortcut declaration.",
    "notes": "Comma-separated alternatives remain one binding declaration and are not counted as separate capabilities."
  },
  {
    "sourceId": "persistence.project-service-public-methods",
    "category": "PERSISTENCE_SERVICE",
    "authorityClaim": "NO_AUTHORITY_CLAIM",
    "extraction": {
      "kind": "TS_PUBLIC_CLASS_METHODS",
      "symbol": "ProjectService",
      "roots": [
        "lib/editron/services/project-service.ts"
      ]
    },
    "observedCount": 56,
    "observedIds": [
      "acquireDirectorMutationLease",
      "acquireTimelineRangeCutLockV1",
      "addOverlay",
      "addOverlayIfAbsent",
      "applyVideoSourceRangeRetimeV1",
      "applyVideoSpeedRampV1",
      "autosaveProject",
      "bindProjectOverlaysToVerifiedProxySourceV1",
      "canAccessProject",
      "captureMutationReceipts",
      "claimDirectorRunV1",
      "claimPhase0RenderedEvidence",
      "commitAudioRightsAttestation",
      "commitMgRenderDelivery",
      "commitPipelineAudioDeliveryV1",
      "commitPipelineVideoDeliveryV1",
      "commitVideoAnalysisDurationCorrectionV1",
      "completeDirectorRunV1",
      "createOrgProject",
      "createProject",
      "createScriptStageProject",
      "cutTimelineRangeV1",
      "deleteOverlay",
      "deleteProject",
      "deriveProjectStatus",
      "failDirectorRunV1",
      "finalizeProjectGeneratedCompositionV1",
      "findProjectBySessionId",
      "getProjectRevision",
      "listOrgProjects",
      "listProjects",
      "loadProject",
      "loadProjectForMutation",
      "preparePipelineDirectorDispatchV1",
      "prepareProjectGeneratedCompositionV1",
      "rebindVideoSourceEventAfterRetimeV1",
      "reconcileProjectDurationFromOverlaysV1",
      "recordChatRenderVerificationProjection",
      "recordDirectorDeliveryFailureV1",
      "recordDirectorProgressV1",
      "recordPhase0ProofFacts",
      "recordPhase0RenderedEvidence",
      "recordPipelineDirectorIntentV1",
      "recordPipelineVideoQualityWarningV1",
      "refreshProjectStatus",
      "releaseDirectorMutationLease",
      "releaseTimelineRangeCutLockV1",
      "relinkProjectProxyToQualifiedMasterV1",
      "replaceOverlayFamilyAtomic",
      "restoreCheckpointState",
      "saveProject",
      "saveProjectWithReceipt",
      "updateOverlay",
      "updateProject",
      "updateProjectMetadata",
      "updateProjectName"
    ],
    "evidencePaths": [
      "lib/editron/services/project-service.ts"
    ],
    "countingSemantics": "Each non-private/non-protected class method is one observed ProjectService method.",
    "notes": "Public method presence does not prove CAS, receipt, proof or planner eligibility."
  },
  {
    "sourceId": "proof.render-delivery-module-candidates",
    "category": "PROOF_RENDER_DELIVERY",
    "authorityClaim": "NO_AUTHORITY_CLAIM",
    "extraction": {
      "kind": "PATH_BASENAME_SCAN",
      "pattern": "non-research lib/editron basenames containing proof|evidence|render|delivery|finaliz",
      "roots": [
        "lib/editron"
      ]
    },
    "observedCount": 121,
    "observedIds": [
      "lib/editron/agent/chat-frame-evidence.ts",
      "lib/editron/motion-graphics/codegen/mg-delivery-record.ts",
      "lib/editron/motion-graphics/codegen/mg-delivery.ts",
      "lib/editron/motion-graphics/codegen/mg-render-job-runner.ts",
      "lib/editron/motion-graphics/codegen/mg-render-job-service.ts",
      "lib/editron/motion-graphics/codegen/render/frame-renderer.ts",
      "lib/editron/motion-graphics/codegen/render/render-moment.ts",
      "lib/editron/motion-graphics/codegen/sandbox-render-worker.ts",
      "lib/editron/motion-graphics/codegen/visual-evidence.ts",
      "lib/editron/motion-graphics/engine/composition-renderer.tsx",
      "lib/editron/motion-graphics/engine/data-viz-renderers.tsx",
      "lib/editron/motion-graphics/engine/eval/render-validity.ts",
      "lib/editron/motion-graphics/engine/eval/rendered-aesthetic.ts",
      "lib/editron/motion-graphics/engine/primitive-renderers.ts",
      "lib/editron/reference-video/enrich-reference-evidence.ts",
      "lib/editron/reference-video/measure-reference-evidence.ts",
      "lib/editron/reference-video/verify-rendered-reference.ts",
      "lib/editron/saas-explainer/explainer-render.ts",
      "lib/editron/saas-explainer/product-evidence-pack.ts",
      "lib/editron/schemas/render-job.ts",
      "lib/editron/services/chapter-renderer.ts",
      "lib/editron/services/chat-edit-render-diagnostics.ts",
      "lib/editron/services/chat-edit-render-verification-dispatch-recovery.ts",
      "lib/editron/services/chat-edit-render-verification-lifecycle.ts",
      "lib/editron/services/chat-edit-render-verification-notification-recovery.ts",
      "lib/editron/services/chat-multimodal-evidence.ts",
      "lib/editron/services/chat-signal-moment-evidence.ts",
      "lib/editron/services/director-delivery-failure.ts",
      "lib/editron/services/editron-brand-vault-evidence.ts",
      "lib/editron/services/media-proxy-master-transcode-prepared-evidence-v2.ts",
      "lib/editron/services/media-source-audio-availability-evidence-mongo-v1.ts",
      "lib/editron/services/media-source-audio-availability-evidence-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-batch-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-dispatch-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-mongo-candidates-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-mongo-ledger-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-recovery-attempt-mongo-document-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-recovery-attempt-policy-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-recovery-mongo-selector-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-recovery-owner-v2.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-recovery-sweep-mongo-document-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-recovery-sweep-mongo-store-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-recovery-sweep-state-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-recovery-sweep-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-run-owner-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-run-record-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-runtime-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-worker-route-v1.ts",
      "lib/editron/services/media-source-audio-version-evidence-store-v1.ts",
      "lib/editron/services/media-source-pts-cadence-scan-finalizer-v1.ts",
      "lib/editron/services/media-source-pts-cadence-scan-finalizer-v3.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-batch-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-dispatch-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-mongo-candidates-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-mongo-ledger-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-recovery-attempt-mongo-document-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-recovery-attempt-policy-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-recovery-mongo-selector-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-recovery-owner-v2.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-recovery-sweep-mongo-document-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-recovery-sweep-mongo-store-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-recovery-sweep-state-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-recovery-sweep-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-run-ledger-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-run-owner-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-run-record-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-runtime-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-worker-route-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-state-owner-v3.ts",
      "lib/editron/services/media-source-version-evidence-mongo-store-v1.ts",
      "lib/editron/services/media-source-version-evidence-owner-v1.ts",
      "lib/editron/services/media-source-version-evidence-retention-v1.ts",
      "lib/editron/services/native-audio-evidence.ts",
      "lib/editron/services/native-media-exact-audio-evidence-v1.ts",
      "lib/editron/services/native-media-final-render-admission-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-ledger-owner-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-ledger-record-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-mongo-ledger-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-policy-mongo-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-policy-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-reservation-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-settlement-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-worker-owner-v1.ts",
      "lib/editron/services/native-media-final-render-ffmpeg-encoder-v1.ts",
      "lib/editron/services/native-media-final-render-materializer-v1.ts",
      "lib/editron/services/native-media-final-render-pcm-equivalence-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-delivery-retry-policy-registry-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-delivery-retry-policy-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-durable-dispatch-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-execution-manifest-mongo-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-execution-manifest-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-job-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-owner-adapter-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-product-route-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-product-runtime-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-result-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-runtime-policy-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-worker-route-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-worker-v1.ts",
      "lib/editron/services/native-media-final-render-prepared-source-publisher-v1.ts",
      "lib/editron/services/native-media-final-render-profile-v1.ts",
      "lib/editron/services/native-media-final-render-r2-private-artifact-v1.ts",
      "lib/editron/services/native-media-final-render-source-preparation-v1.ts",
      "lib/editron/services/native-media-final-render-source-rights-owner-v1.ts",
      "lib/editron/services/phase0-render-artifact-pack.ts",
      "lib/editron/services/phase0-rendered-aesthetic-scoring.ts",
      "lib/editron/services/phase0-rendered-evidence-worker.ts",
      "lib/editron/services/pipeline-audio-project-delivery-v1.ts",
      "lib/editron/services/pipeline-video-project-delivery-v1.ts",
      "lib/editron/services/project-selected-source-audio-evidence-v1.ts",
      "lib/editron/services/render-audio-rights-authority.ts",
      "lib/editron/services/render-chapter-retention.ts",
      "lib/editron/services/render-delivery-manifest.ts",
      "lib/editron/services/render-finalization-dispatch.ts",
      "lib/editron/services/render-finalizer-client.ts",
      "lib/editron/services/render-job-service.ts",
      "lib/editron/services/transition-render-form.ts",
      "lib/editron/services/visual-evidence-scorer.ts",
      "lib/editron/shared/render-request-payload.ts"
    ],
    "evidencePaths": [
      "lib/editron/agent/chat-frame-evidence.ts",
      "lib/editron/motion-graphics/codegen/mg-delivery-record.ts",
      "lib/editron/motion-graphics/codegen/mg-delivery.ts",
      "lib/editron/motion-graphics/codegen/mg-render-job-runner.ts",
      "lib/editron/motion-graphics/codegen/mg-render-job-service.ts",
      "lib/editron/motion-graphics/codegen/render/frame-renderer.ts",
      "lib/editron/motion-graphics/codegen/render/render-moment.ts",
      "lib/editron/motion-graphics/codegen/sandbox-render-worker.ts",
      "lib/editron/motion-graphics/codegen/visual-evidence.ts",
      "lib/editron/motion-graphics/engine/composition-renderer.tsx",
      "lib/editron/motion-graphics/engine/data-viz-renderers.tsx",
      "lib/editron/motion-graphics/engine/eval/render-validity.ts",
      "lib/editron/motion-graphics/engine/eval/rendered-aesthetic.ts",
      "lib/editron/motion-graphics/engine/primitive-renderers.ts",
      "lib/editron/reference-video/enrich-reference-evidence.ts",
      "lib/editron/reference-video/measure-reference-evidence.ts",
      "lib/editron/reference-video/verify-rendered-reference.ts",
      "lib/editron/saas-explainer/explainer-render.ts",
      "lib/editron/saas-explainer/product-evidence-pack.ts",
      "lib/editron/schemas/render-job.ts",
      "lib/editron/services/chapter-renderer.ts",
      "lib/editron/services/chat-edit-render-diagnostics.ts",
      "lib/editron/services/chat-edit-render-verification-dispatch-recovery.ts",
      "lib/editron/services/chat-edit-render-verification-lifecycle.ts",
      "lib/editron/services/chat-edit-render-verification-notification-recovery.ts",
      "lib/editron/services/chat-multimodal-evidence.ts",
      "lib/editron/services/chat-signal-moment-evidence.ts",
      "lib/editron/services/director-delivery-failure.ts",
      "lib/editron/services/editron-brand-vault-evidence.ts",
      "lib/editron/services/media-proxy-master-transcode-prepared-evidence-v2.ts",
      "lib/editron/services/media-source-audio-availability-evidence-mongo-v1.ts",
      "lib/editron/services/media-source-audio-availability-evidence-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-batch-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-dispatch-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-mongo-candidates-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-mongo-ledger-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-recovery-attempt-mongo-document-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-recovery-attempt-policy-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-recovery-mongo-selector-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-recovery-owner-v2.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-recovery-sweep-mongo-document-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-recovery-sweep-mongo-store-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-recovery-sweep-state-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-recovery-sweep-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-run-owner-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-run-record-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-runtime-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-worker-route-v1.ts",
      "lib/editron/services/media-source-audio-version-evidence-store-v1.ts",
      "lib/editron/services/media-source-pts-cadence-scan-finalizer-v1.ts",
      "lib/editron/services/media-source-pts-cadence-scan-finalizer-v3.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-batch-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-dispatch-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-mongo-candidates-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-mongo-ledger-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-recovery-attempt-mongo-document-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-recovery-attempt-policy-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-recovery-mongo-selector-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-recovery-owner-v2.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-recovery-sweep-mongo-document-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-recovery-sweep-mongo-store-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-recovery-sweep-state-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-recovery-sweep-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-run-ledger-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-run-owner-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-run-record-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-runtime-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-worker-route-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-state-owner-v3.ts",
      "lib/editron/services/media-source-version-evidence-mongo-store-v1.ts",
      "lib/editron/services/media-source-version-evidence-owner-v1.ts",
      "lib/editron/services/media-source-version-evidence-retention-v1.ts",
      "lib/editron/services/native-audio-evidence.ts",
      "lib/editron/services/native-media-exact-audio-evidence-v1.ts",
      "lib/editron/services/native-media-final-render-admission-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-ledger-owner-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-ledger-record-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-mongo-ledger-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-policy-mongo-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-policy-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-reservation-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-settlement-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-worker-owner-v1.ts",
      "lib/editron/services/native-media-final-render-ffmpeg-encoder-v1.ts",
      "lib/editron/services/native-media-final-render-materializer-v1.ts",
      "lib/editron/services/native-media-final-render-pcm-equivalence-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-delivery-retry-policy-registry-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-delivery-retry-policy-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-durable-dispatch-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-execution-manifest-mongo-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-execution-manifest-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-job-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-owner-adapter-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-product-route-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-product-runtime-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-result-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-runtime-policy-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-worker-route-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-worker-v1.ts",
      "lib/editron/services/native-media-final-render-prepared-source-publisher-v1.ts",
      "lib/editron/services/native-media-final-render-profile-v1.ts",
      "lib/editron/services/native-media-final-render-r2-private-artifact-v1.ts",
      "lib/editron/services/native-media-final-render-source-preparation-v1.ts",
      "lib/editron/services/native-media-final-render-source-rights-owner-v1.ts",
      "lib/editron/services/phase0-render-artifact-pack.ts",
      "lib/editron/services/phase0-rendered-aesthetic-scoring.ts",
      "lib/editron/services/phase0-rendered-evidence-worker.ts",
      "lib/editron/services/pipeline-audio-project-delivery-v1.ts",
      "lib/editron/services/pipeline-video-project-delivery-v1.ts",
      "lib/editron/services/project-selected-source-audio-evidence-v1.ts",
      "lib/editron/services/render-audio-rights-authority.ts",
      "lib/editron/services/render-chapter-retention.ts",
      "lib/editron/services/render-delivery-manifest.ts",
      "lib/editron/services/render-finalization-dispatch.ts",
      "lib/editron/services/render-finalizer-client.ts",
      "lib/editron/services/render-job-service.ts",
      "lib/editron/services/transition-render-form.ts",
      "lib/editron/services/visual-evidence-scorer.ts",
      "lib/editron/shared/render-request-payload.ts"
    ],
    "countingSemantics": "Each matching current source module path is one proof/render/delivery candidate surface.",
    "notes": "Filename discovery is intentionally broad; Phase 3 must identify owners, consumers, duplicates and dead modules."
  },
  {
    "sourceId": "render.layer-content-overlay-cases",
    "category": "RENDER_CONSUMER",
    "authorityClaim": "NO_AUTHORITY_CLAIM",
    "extraction": {
      "kind": "TS_SWITCH_ENUM_CASES",
      "symbol": "LayerContent switch on OverlayType",
      "roots": [
        "components/editron/editor/version-7.0.0/components/core/layer-content.tsx"
      ]
    },
    "observedCount": 13,
    "observedIds": [
      "CAPTION",
      "GENERATED_SCENE",
      "HTML_SCENE",
      "HTML_STICKER",
      "IMAGE",
      "MG_SEQUENCE",
      "MOTION_GRAPHIC",
      "SHAPE",
      "SOUND",
      "STICKER",
      "TEXT",
      "TRANSITION",
      "VIDEO"
    ],
    "evidencePaths": [
      "components/editron/editor/version-7.0.0/components/core/layer-content.tsx"
    ],
    "countingSemantics": "Each unique OverlayType case in LayerContent is one observed main renderer case.",
    "notes": "Grouped cases are counted by enum case. Default null and side-panel-only overlay types are not renderer support."
  },
  {
    "sourceId": "state.overlay-type-declarations",
    "category": "STATE_TYPE",
    "authorityClaim": "NO_AUTHORITY_CLAIM",
    "extraction": {
      "kind": "TS_ENUM_STRING_VALUES",
      "symbol": "OverlayType",
      "roots": [
        "components/editron/editor/version-7.0.0/types.ts"
      ]
    },
    "observedCount": 22,
    "observedIds": [
      "ai-chat",
      "ai-suggestions",
      "caption",
      "generated-scene",
      "html-scene",
      "html-sticker",
      "image",
      "local-dir",
      "lottie",
      "mg-sequence",
      "motion-graphic",
      "quality-review",
      "scan-report",
      "sfx-library",
      "shape",
      "sound",
      "sticker",
      "template",
      "text",
      "transition",
      "transitions",
      "video"
    ],
    "evidencePaths": [
      "components/editron/editor/version-7.0.0/types.ts"
    ],
    "countingSemantics": "Each OverlayType enum string value is one observed editor state discriminator.",
    "notes": "The enum contains both timeline-rendered media and panel-only/non-rendered state."
  },
  {
    "sourceId": "worker.job-module-candidates",
    "category": "WORKER_JOB",
    "authorityClaim": "NO_AUTHORITY_CLAIM",
    "extraction": {
      "kind": "PATH_BASENAME_SCAN",
      "pattern": "non-research lib/editron basename token job|worker|runner|dispatch",
      "roots": [
        "lib/editron"
      ]
    },
    "observedCount": 57,
    "observedIds": [
      "lib/editron/motion-graphics/codegen/mg-design-job-runner.ts",
      "lib/editron/motion-graphics/codegen/mg-render-job-runner.ts",
      "lib/editron/motion-graphics/codegen/mg-render-job-service.ts",
      "lib/editron/motion-graphics/codegen/sandbox-render-worker.ts",
      "lib/editron/motion-graphics/codegen/worker-contract.ts",
      "lib/editron/saas-explainer/explainer-job-service.ts",
      "lib/editron/schemas/render-job.ts",
      "lib/editron/security/internal-worker-auth.ts",
      "lib/editron/services/asset-analysis-worker-policy.ts",
      "lib/editron/services/audio-worker-dispatch.ts",
      "lib/editron/services/chat-deep-analysis-job.ts",
      "lib/editron/services/chat-dubbing-job.ts",
      "lib/editron/services/chat-edit-render-verification-dispatch-recovery.ts",
      "lib/editron/services/chat-editorial-intent-job.ts",
      "lib/editron/services/chat-reference-style-job.ts",
      "lib/editron/services/durable-workflow-job-store-v1.ts",
      "lib/editron/services/durable-workflow-job-v1.ts",
      "lib/editron/services/durable-workflow-qstash-dispatch-v1.ts",
      "lib/editron/services/editorial-plan-durable-job-binding-v1.ts",
      "lib/editron/services/editorial-plan-durable-job-resolver-v1.ts",
      "lib/editron/services/editorial-plan-durable-worker-v1.ts",
      "lib/editron/services/editorial-plan-product-dispatch-v1.ts",
      "lib/editron/services/editorial-plan-product-worker-v1.ts",
      "lib/editron/services/media-proxy-master-transcode-durable-dispatch-v1.ts",
      "lib/editron/services/media-proxy-master-transcode-durable-dispatch-v2.ts",
      "lib/editron/services/media-proxy-master-transcode-durable-job-v1.ts",
      "lib/editron/services/media-proxy-master-transcode-durable-job-v2.ts",
      "lib/editron/services/media-proxy-master-transcode-durable-worker-route-v1.ts",
      "lib/editron/services/media-proxy-master-transcode-durable-worker-v1.ts",
      "lib/editron/services/media-proxy-master-transcode-durable-worker-v2.ts",
      "lib/editron/services/media-proxy-master-transcode-execution-budget-worker-owner-v1.ts",
      "lib/editron/services/media-proxy-master-transcode-execution-budget-worker-owner-v2.ts",
      "lib/editron/services/media-proxy-master-transcode-product-runtime-dispatch-v2.ts",
      "lib/editron/services/media-source-audio-durable-dispatch-v1.ts",
      "lib/editron/services/media-source-audio-durable-job-v1.ts",
      "lib/editron/services/media-source-audio-durable-worker-route-v1.ts",
      "lib/editron/services/media-source-audio-durable-worker-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-dispatch-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-worker-route-v1.ts",
      "lib/editron/services/media-source-pts-cadence-durable-dispatch-v1.ts",
      "lib/editron/services/media-source-pts-cadence-durable-dispatch-v3.ts",
      "lib/editron/services/media-source-pts-cadence-durable-job-binding-v1.ts",
      "lib/editron/services/media-source-pts-cadence-durable-job-binding-v3.ts",
      "lib/editron/services/media-source-pts-cadence-durable-worker-route-v1.ts",
      "lib/editron/services/media-source-pts-cadence-durable-worker-route-v3.ts",
      "lib/editron/services/media-source-pts-cadence-durable-worker-v1.ts",
      "lib/editron/services/media-source-pts-cadence-durable-worker-v3.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-dispatch-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-worker-route-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-worker-owner-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-durable-dispatch-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-job-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-worker-route-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-worker-v1.ts",
      "lib/editron/services/phase0-rendered-evidence-worker.ts",
      "lib/editron/services/render-finalization-dispatch.ts",
      "lib/editron/services/render-job-service.ts"
    ],
    "evidencePaths": [
      "lib/editron/motion-graphics/codegen/mg-design-job-runner.ts",
      "lib/editron/motion-graphics/codegen/mg-render-job-runner.ts",
      "lib/editron/motion-graphics/codegen/mg-render-job-service.ts",
      "lib/editron/motion-graphics/codegen/sandbox-render-worker.ts",
      "lib/editron/motion-graphics/codegen/worker-contract.ts",
      "lib/editron/saas-explainer/explainer-job-service.ts",
      "lib/editron/schemas/render-job.ts",
      "lib/editron/security/internal-worker-auth.ts",
      "lib/editron/services/asset-analysis-worker-policy.ts",
      "lib/editron/services/audio-worker-dispatch.ts",
      "lib/editron/services/chat-deep-analysis-job.ts",
      "lib/editron/services/chat-dubbing-job.ts",
      "lib/editron/services/chat-edit-render-verification-dispatch-recovery.ts",
      "lib/editron/services/chat-editorial-intent-job.ts",
      "lib/editron/services/chat-reference-style-job.ts",
      "lib/editron/services/durable-workflow-job-store-v1.ts",
      "lib/editron/services/durable-workflow-job-v1.ts",
      "lib/editron/services/durable-workflow-qstash-dispatch-v1.ts",
      "lib/editron/services/editorial-plan-durable-job-binding-v1.ts",
      "lib/editron/services/editorial-plan-durable-job-resolver-v1.ts",
      "lib/editron/services/editorial-plan-durable-worker-v1.ts",
      "lib/editron/services/editorial-plan-product-dispatch-v1.ts",
      "lib/editron/services/editorial-plan-product-worker-v1.ts",
      "lib/editron/services/media-proxy-master-transcode-durable-dispatch-v1.ts",
      "lib/editron/services/media-proxy-master-transcode-durable-dispatch-v2.ts",
      "lib/editron/services/media-proxy-master-transcode-durable-job-v1.ts",
      "lib/editron/services/media-proxy-master-transcode-durable-job-v2.ts",
      "lib/editron/services/media-proxy-master-transcode-durable-worker-route-v1.ts",
      "lib/editron/services/media-proxy-master-transcode-durable-worker-v1.ts",
      "lib/editron/services/media-proxy-master-transcode-durable-worker-v2.ts",
      "lib/editron/services/media-proxy-master-transcode-execution-budget-worker-owner-v1.ts",
      "lib/editron/services/media-proxy-master-transcode-execution-budget-worker-owner-v2.ts",
      "lib/editron/services/media-proxy-master-transcode-product-runtime-dispatch-v2.ts",
      "lib/editron/services/media-source-audio-durable-dispatch-v1.ts",
      "lib/editron/services/media-source-audio-durable-job-v1.ts",
      "lib/editron/services/media-source-audio-durable-worker-route-v1.ts",
      "lib/editron/services/media-source-audio-durable-worker-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-dispatch-v1.ts",
      "lib/editron/services/media-source-audio-evidence-backfill-worker-route-v1.ts",
      "lib/editron/services/media-source-pts-cadence-durable-dispatch-v1.ts",
      "lib/editron/services/media-source-pts-cadence-durable-dispatch-v3.ts",
      "lib/editron/services/media-source-pts-cadence-durable-job-binding-v1.ts",
      "lib/editron/services/media-source-pts-cadence-durable-job-binding-v3.ts",
      "lib/editron/services/media-source-pts-cadence-durable-worker-route-v1.ts",
      "lib/editron/services/media-source-pts-cadence-durable-worker-route-v3.ts",
      "lib/editron/services/media-source-pts-cadence-durable-worker-v1.ts",
      "lib/editron/services/media-source-pts-cadence-durable-worker-v3.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-dispatch-v1.ts",
      "lib/editron/services/media-source-pts-cadence-version-evidence-backfill-worker-route-v1.ts",
      "lib/editron/services/native-media-final-render-execution-budget-worker-owner-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-durable-dispatch-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-job-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-worker-route-v1.ts",
      "lib/editron/services/native-media-final-render-preparation-worker-v1.ts",
      "lib/editron/services/phase0-rendered-evidence-worker.ts",
      "lib/editron/services/render-finalization-dispatch.ts",
      "lib/editron/services/render-job-service.ts"
    ],
    "countingSemantics": "Each matching current source module path is one worker/job candidate surface.",
    "notes": "Filename discovery is intentionally broad and does not establish dispatch reachability, authentication or authority."
  }
] as const,
);

function compareCodeUnits(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function sortedUnique(values: readonly string[]): string[] {
  return [...new Set(values)].sort(compareCodeUnits);
}

export const CAP2_CURRENT_TRUTH_SOURCE_PATHS_V11 = deepFreeze(
  sortedUnique(CAP2_CURRENT_TRUTH_SOURCE_OBSERVATIONS_V11.flatMap(
    ({ evidencePaths }) => evidencePaths,
  )),
);
export type Cap2CurrentTruthDomainV11 = Cap2CurrentTruthDomainV10;
export const getCap2CurrentTruthDomainEvidencePathsV11 =
  getCap2CurrentTruthDomainEvidencePathsV10;
export const hashNormalizedCap2FileV11 = hashNormalizedCap2FileV10;
export const hashNormalizedCap2SourceSnapshotV11 =
  hashNormalizedCap2SourceSnapshotV10;

const agencySupportClassMaterial = {
  classId: 'AGENCY_100GB_4H_V1' as const,
  freezeVersion: 1 as const,
  disposition: 'DECLARED_SUPPORTED_SUBCLASSES_IMPLEMENTATION_OPEN' as const,
  sourceBasis: {
    acceptedAgencyAdr: {
      path: 'docs/editron/editron-agency-vfx-finishing-relight-adr-2026-08-31.md' as const,
      normalizedSha256: '03d1f2143b721b06c2690089c499e4aec0538d9767c221a0fc27408bc5e1070d' as const,
      status: 'ACCEPTED_SCOPE_IMPLEMENTATION_OPEN' as const,
    },
    canonicalPlan: {
      path: 'docs/EDITRON_FINAL_EXECUTION_PLAN_2026-08-10.md' as const,
      requirement: 'FREEZE_EXACT_AGENCY_SUBCLASSES_AND_PROOFS_WITHOUT_CLAIMING_ALL_FILM_POST_VARIANTS' as const,
    },
  },
  eligibility: {
    envelope: '100_GB_TOTAL_INGESTED_SOURCE_BYTES_FOUR_HOUR_AGGREGATE_RAW_SOURCE_DURATION' as const,
    media: 'RIGHTS_CLEARED_MEDIA_ONLY' as const,
    requiredIdentity: [
      'PROJECT_ID',
      'SOURCE_VERSION',
      'STREAM',
      'EPOCH',
      'TIMELINE_RANGE',
    ] as const,
    preservation: [
      'IMMUTABLE_INPUT_MEDIA',
      'PROXY_MASTER_MAPPING',
      'VERSIONED_SEQUENCE_IDENTITY',
    ] as const,
    operationBoundary: 'DECLARED_RANGE_SCOPED_EDITABLE_OPERATIONS_ONLY' as const,
    deliveryBoundary: 'DECLARED_OUTPUT_AND_IMF_SPEC_ONLY' as const,
  },
  ceilings: [
    'TOTAL_INGESTED_SOURCE_BYTES_AT_OR_BELOW_100_GB',
    'AGGREGATE_RAW_SOURCE_DURATION_AT_OR_BELOW_FOUR_HOURS',
    'NO_UNDECLARED_CODEC_CAMERA_COLOUR_OR_DELIVERY_PROFILE',
    'NO_OPERATION_OUTSIDE_DECLARED_TIMELINE_RANGE',
  ] as const,
  admission: 'STOP_AT_FIRST_OF_TOTAL_INGESTED_SOURCE_BYTES_100_GB_OR_AGGREGATE_RAW_SOURCE_DURATION_FOUR_HOURS' as const,
  stopAtFirst: [
    'RIGHTS_OR_EGRESS_GATE_FAILS',
    'SOURCE_VERSION_STREAM_EPOCH_OR_RANGE_IDENTITY_MISSING',
    'PROXY_MASTER_MAPPING_OR_INPUT_IMMUTABILITY_UNVERIFIED',
    'REQUIRED_FAMILY_PROOF_MISSING_INVALID_OR_NON_REPRODUCIBLE',
    'OUTPUT_OR_IMF_DECLARATION_OR_VALIDATION_MISSING',
    'ARCHIVE_RESTORE_RELINK_REREAD_OR_RERENDER_VERIFICATION_FAILS',
  ] as const,
  requiredFamilyIds: [
    'agency.vfx.masks-mattes-roto-keying-tracking',
    'agency.vfx.plates-exr-vfx-pulls',
    'agency.colour.temporally-consistent-relighting',
    'agency.finishing.conform-reconform-change-lists',
    'agency.delivery.mastering',
    'agency.delivery.declared-imf-class',
    'agency.recovery.archive-restore',
  ] as const,
  proofChainStages: [
    'CALLER',
    'DECISION_OWNER',
    'FORM_OWNER',
    'MUTATION_OWNER',
    'STORED_STATE_REVISION',
    'RENDERER',
    'PROOF',
  ] as const,
  sourceTruth: {
    status: 'RESEARCH_SOURCE_SURFACES_NO_OWNER_CERTIFIED' as const,
    observationIds: [
      'api.editron-linked-route-exports',
      'persistence.project-service-public-methods',
      'proof.render-delivery-module-candidates',
      'worker.job-module-candidates',
    ] as const,
  },
  currentStatus: {
    implementation: 'IMPLEMENTATION_OPEN' as const,
    sourceOwnership: 'NO_OWNER_CERTIFIED' as const,
    relighting: 'NO_PRODUCT_OWNER_OR_EXECUTABLE_CAPABILITY_FOUND' as const,
    movingMattesAndTracking: 'EXPLICIT_CAPABILITY_GAP' as const,
    conformImfAndArchive: 'PROFESSIONAL_PATHS_NOT_FOUND' as const,
    proxyMasterFoundations: 'FOUNDATIONS_PRESENT_NOT_PROFESSIONAL_SYSTEM' as const,
    fullEnvelopeEvidence: 'NOT_RUN' as const,
  },
  openGaps: [
    'RELIGHT_PRODUCT_OWNER_AND_EXECUTABLE_CAPABILITY',
    'MOVING_MATTE_AND_TRACKED_FINE_CONTOUR_CAPABILITY',
    'PROFESSIONAL_RECONFORM_CHANGE_LIST_IMF_VFX_PULL_AND_ARCHIVE_RESTORE_PATHS',
    'FULL_100_GB_TOTAL_INGESTED_SOURCE_BYTES_FOUR_HOUR_AGGREGATE_RAW_SOURCE_DURATION_FIXTURE_AND_QUALIFIED_REVIEWER',
  ] as const,
  capabilitySourceDeliveryRows: [
    {
      rowId: 'agency.vfx.masks-mattes-roto-keying-tracking',
      layer: 'CAPABILITY' as const,
      declaredSubclass: 'CANONICAL_MASKS_MATTES_ROTOSCOPING_KEYING_TRACKING_V1' as const,
      currentSourceObservationIds: [
        'proof.render-delivery-module-candidates',
        'worker.job-module-candidates',
      ] as const,
      eligibleForms: [
        'VECTOR_OBJECT_MASKS_FEATHER_EXPANSION_INVERSION_ALPHA_MODES',
        'EDITABLE_TEMPORAL_MATTES_MANUAL_ROTO_CORRECTION_STROKES',
        'CHROMA_KEYING_SPILL_AND_EDGE_CONTROLS',
        'POINT_PLANAR_OBJECT_FACE_TRACKING',
      ] as const,
      requiredProofs: [
        'CANONICAL_COMPOSITING_STATE_AND_RENDERER_IDENTITY',
        'MOVING_HAIR_OCCLUSION_TRANSPARENCY_REFLECTION_AND_KEYING_EDGE_CASES',
        'SUBJECT_CAMERA_MOVEMENT_AND_TRACK_LOSS',
        'PREVIEW_CORRECTION_SAVE_RELOAD_PROXY_MASTER_RELINK_RENDER_UNDO_TURNOVER',
      ] as const,
    },
    {
      rowId: 'agency.vfx.plates-exr-vfx-pulls',
      layer: 'SOURCE' as const,
      declaredSubclass: 'PLATES_EXR_INTERCHANGE_VFX_PULLS_WITH_HANDLES_AND_IDENTITY_V1' as const,
      currentSourceObservationIds: [
        'api.editron-linked-route-exports',
        'proof.render-delivery-module-candidates',
        'worker.job-module-candidates',
      ] as const,
      eligibleForms: [
        'PLATE_AND_MATTE_SOURCE_VERSION_IDENTITY',
        'EXR_SEQUENCE_CHANNEL_ALPHA_COLOUR_METADATA_FOR_DECLARED_FORMATS',
        'VFX_PULL_SOURCE_HANDLES_SHOT_TASK_VERSION_BURN_INS_CHECKSUMS',
      ] as const,
      requiredProofs: [
        'EXR_PLATE_VFX_PULL_ROUND_TRIP',
        'SOURCE_HANDLE_AND_IDENTITY_RELOAD_PROOF',
        'PREVIEW_CORRECTION_SAVE_RELOAD_PROXY_MASTER_RELINK_RENDER_UNDO_TURNOVER',
      ] as const,
    },
    {
      rowId: 'agency.colour.temporally-consistent-relighting',
      layer: 'CAPABILITY' as const,
      declaredSubclass: 'NON_DESTRUCTIVE_TEMPORALLY_CONSISTENT_RELIGHTING_V1' as const,
      currentSourceObservationIds: [
        'proof.render-delivery-module-candidates',
        'worker.job-module-candidates',
      ] as const,
      eligibleForms: [
        'RANGE_SCOPED_EDITABLE_NON_DESTRUCTIVE_EFFECT',
        'DECLARED_DEPTH_SUBJECT_REGION_TEMPORAL_CONFIDENCE_EVIDENCE',
        'EDITABLE_LIGHT_DIRECTION_INTENSITY_FALLOFF_WARMTH_PROTECTED_REGIONS',
      ] as const,
      requiredProofs: [
        'SKIN_TONE_HIGHLIGHT_SHADOW_HALO_EDGE_AND_FLICKER_PROOF',
        'SAFE_STOP_FOR_CLIPPED_CRUSHED_BLUR_REFLECTIVE_TRANSPARENT_FINE_HAIR_UNCERTAIN_DEPTH',
        'PREVIEW_FINAL_RENDER_UNDO_REPLAY_RELOAD_AND_ARCHIVE_BEHAVIOUR',
        'MODEL_RUNTIME_CHECKPOINT_AND_COMMERCIAL_RIGHTS_IDENTITY',
      ] as const,
    },
    {
      rowId: 'agency.finishing.conform-reconform-change-lists',
      layer: 'DELIVERY' as const,
      declaredSubclass: 'ONLINE_CONFORM_RECONFORM_CHANGE_LISTS_V1' as const,
      currentSourceObservationIds: [
        'persistence.project-service-public-methods',
        'proof.render-delivery-module-candidates',
      ] as const,
      eligibleForms: [
        'PICTURE_LOCK_AND_VERSION_IDENTITY',
        'VERIFIED_PROXY_TO_MASTER_CONFORM',
        'DETERMINISTIC_RECONFORM',
        'HUMAN_READABLE_AND_MACHINE_READABLE_CHANGE_LIST',
      ] as const,
      requiredProofs: [
        'APPROVED_SEQUENCE_TO_PICTURE_LOCK_TO_MASTER_SOURCE_RENDER_QC',
        'EDITORIAL_CHANGE_AFTER_LOCK_RECONFORM_AND_CHANGE_LIST',
        'PROXY_MASTER_RELINK_AFTER_VFX_AND_RELIGHT_EDITS',
      ] as const,
    },
    {
      rowId: 'agency.delivery.mastering',
      layer: 'DELIVERY' as const,
      declaredSubclass: 'VERSIONED_MASTERING_WITH_MASTER_SOURCE_QC_V1' as const,
      currentSourceObservationIds: [
        'api.editron-linked-route-exports',
        'proof.render-delivery-module-candidates',
        'worker.job-module-candidates',
      ] as const,
      eligibleForms: [
        'MASTER_SOURCE_RENDER_AND_QC',
        'VERSIONED_MASTER_IDENTITY',
        'ORDINARY_DECLARED_DELIVERY_OUTPUT',
      ] as const,
      requiredProofs: [
        'MASTER_SOURCE_RENDER_AND_INDEPENDENT_QC',
        'VERSIONED_MASTER_REREAD_AND_OUTPUT_VERIFICATION',
        'EXACT_PERCEPTUAL_AND_HUMAN_EVIDENCE_WITH_CORRECTION_TIME_AND_COMPLETE_COST',
      ] as const,
    },
    {
      rowId: 'agency.delivery.declared-imf-class',
      layer: 'DELIVERY' as const,
      declaredSubclass: 'DECLARED_AGENCY_IMF_CLASS_V1' as const,
      currentSourceObservationIds: [
        'api.editron-linked-route-exports',
        'proof.render-delivery-module-candidates',
        'worker.job-module-candidates',
      ] as const,
      eligibleForms: [
        'AGENCY_IMF_APPLICATION_CONSTRAINTS_ESSENCE_CODECS_AUDIO_LAYOUTS_CAPTIONS_SUPPLEMENTS_IDENTIFIERS',
        'INDEPENDENT_IMF_PACKAGE_VALIDATION',
      ] as const,
      requiredProofs: [
        'ORDINARY_DELIVERY_PLUS_DECLARED_IMF_PACKAGE_AND_INDEPENDENT_VALIDATION',
        'PACKAGE_IDENTITIES_ESSENCE_METADATA_AND_VALIDATOR_RECEIPT',
        'NO_ZIP_OR_UNVALIDATED_ARCHIVE_SUBSTITUTES_FOR_IMF',
      ] as const,
    },
    {
      rowId: 'agency.recovery.archive-restore',
      layer: 'DELIVERY' as const,
      declaredSubclass: 'CONTENT_ADDRESSED_ARCHIVE_AND_FRESH_ENVIRONMENT_RESTORE_V1' as const,
      currentSourceObservationIds: [
        'api.editron-linked-route-exports',
        'proof.render-delivery-module-candidates',
        'worker.job-module-candidates',
      ] as const,
      eligibleForms: [
        'CONTENT_ADDRESSED_ARCHIVE_MANIFEST',
        'INTERRUPTION_SAFE_ARCHIVE_CREATION',
        'FRESH_ISOLATED_RUNTIME_RESTORE',
        'RELINK_REREAD_AND_RERENDER_VERIFICATION',
      ] as const,
      requiredProofs: [
        'INTERRUPTED_ARCHIVE_CREATION',
        'CLEAN_ENVIRONMENT_RESTORATION_DRILL',
        'RESTORE_RELINK_REREAD_RERENDER_VERIFICATION',
      ] as const,
    },
  ] as const,
  declaredAgencyImfClass: {
    classId: 'AGENCY_IMF_DECLARED_CLASS_V1' as const,
    applicationConstraints: [
      'ONE_DECLARED_AGENCY_APPLICATION_PROFILE',
      'DECLARED_TIMELINE_AND_VERSION_IDENTITY',
      'VALIDATED_PACKAGE_MANIFEST_REQUIRED',
    ] as const,
    essenceCodecs: [
      'DECLARED_PICTURE_ESSENCE_CODEC_AND_PROFILE',
      'DECLARED_AUDIO_ESSENCE_CODEC_AND_PROFILE',
    ] as const,
    audioLayouts: ['DECLARED_AUDIO_LAYOUT'] as const,
    captionsSubtitles: ['DECLARED_CAPTION_SUBTITLE_PROFILE'] as const,
    supplementalVersions: ['EXPLICITLY_DECLARED_SUPPLEMENTAL_VERSION_SET'] as const,
    identifiers: [
      'CONTENT_ID',
      'COMPOSITION_ID',
      'PACKAGE_ID',
      'ESSENCE_ID',
    ] as const,
    validator: 'INDEPENDENT_DECLARED_IMF_VALIDATOR_REQUIRED' as const,
    status: 'DECLARATION_ONLY_NO_IMPLEMENTATION_OR_CERTIFICATION' as const,
  },
  proofRequirements: [
    'EVERY_ROW_CALLER_TO_DECISION_OWNER_TO_FORM_OWNER_TO_MUTATION_OWNER_TO_RENDERER_TO_PROOF',
    'FAST_DETERMINISTIC_CLIP_SEMANTICS_AND_SAFE_STOPS',
    'RIGHTS_CLEARED_FULL_100_GB_TOTAL_INGESTED_SOURCE_BYTES_FOUR_HOUR_AGGREGATE_RAW_SOURCE_DURATION_FIXTURE',
    'EXACT_PERCEPTUAL_AND_HUMAN_EVIDENCE_WITH_CORRECTION_TIME_AND_COMPLETE_COST',
    'ISOLATED_COMPONENT_COVERAGE_IS_NOT_AGENCY_CLOSURE',
  ] as const,
  explicitExclusions: [
    {
      exclusionId: 'agency.capacity-beyond-100gb-four-hours',
      disposition: 'LATER_FILM_POST_VARIANT' as const,
      statement: 'Five-hour and ten-hour capacity targets and any envelope beyond 100 GB total ingested source bytes or four hours aggregate raw source duration are outside this first agency class.',
    },
    {
      exclusionId: 'agency.production-house-film-post-certification',
      disposition: 'LATER_FILM_POST_VARIANT' as const,
      statement: 'Production-house and film-post accepted-run certification remains later Stage 8 work.',
    },
    {
      exclusionId: 'agency.camera-card-dailies-multicam',
      disposition: 'LATER_FILM_POST_VARIANT' as const,
      statement: 'Camera-card/reel/audio-roll and dailies workflows, script sync and high-end multicam subclasses are not frozen here.',
    },
    {
      exclusionId: 'agency.raw-log-managed-colour-hdr-scopes',
      disposition: 'LATER_FILM_POST_VARIANT' as const,
      statement: 'Full RAW/log/managed-colour/HDR/scopes certification is outside this bounded agency subclass.',
    },
    {
      exclusionId: 'agency.adr-restoration-audio-buses-atmos',
      disposition: 'LATER_FILM_POST_VARIANT' as const,
      statement: 'ADR/restoration/buses/automation/stems/surround/Atmos handoff remains a later film-post variant.',
    },
    {
      exclusionId: 'agency.undeclared-imf-variant',
      disposition: 'EXPLICITLY_INELIGIBLE' as const,
      statement: 'An undeclared IMF application, codec, audio, caption, supplemental-version or identifier variant is not eligible for this class.',
    },
    {
      exclusionId: 'agency.unclassified-capability-row',
      disposition: 'EXPLICITLY_INELIGIBLE' as const,
      statement: 'CAP rows outside this frozen capability/source/delivery matrix retain their owning stage; no row is deferred by guess.',
    },
  ] as const,
  authority: {
    declaration: 'SUPPORTED_SUBCLASS_DECLARATION_ONLY' as const,
    implementationStatus: 'IMPLEMENTATION_OPEN' as const,
    certified: false as const,
    productionEligible: false as const,
    runtimeMutationAuthorized: false as const,
    readinessReceipt: 'NOT_A_READINESS_RECEIPT' as const,
    catalogPromotion: false as const,
  },
} as const;

export const agency100Gb4hV1SupportClassFreezeSchema = z.object({
  classId: z.literal('AGENCY_100GB_4H_V1'),
  freezeVersion: z.literal(1),
  disposition: z.literal('DECLARED_SUPPORTED_SUBCLASSES_IMPLEMENTATION_OPEN'),
  sourceBasis: z.object({
    acceptedAgencyAdr: z.object({
      path: z.literal('docs/editron/editron-agency-vfx-finishing-relight-adr-2026-08-31.md'),
      normalizedSha256: z.literal('03d1f2143b721b06c2690089c499e4aec0538d9767c221a0fc27408bc5e1070d'),
      status: z.literal('ACCEPTED_SCOPE_IMPLEMENTATION_OPEN'),
    }).strict(),
    canonicalPlan: z.object({
      path: z.literal('docs/EDITRON_FINAL_EXECUTION_PLAN_2026-08-10.md'),
      requirement: z.literal('FREEZE_EXACT_AGENCY_SUBCLASSES_AND_PROOFS_WITHOUT_CLAIMING_ALL_FILM_POST_VARIANTS'),
    }).strict(),
  }).strict(),
  eligibility: z.object({
    envelope: z.literal('100_GB_TOTAL_INGESTED_SOURCE_BYTES_FOUR_HOUR_AGGREGATE_RAW_SOURCE_DURATION'),
    media: z.literal('RIGHTS_CLEARED_MEDIA_ONLY'),
    requiredIdentity: z.tuple([
      z.literal('PROJECT_ID'),
      z.literal('SOURCE_VERSION'),
      z.literal('STREAM'),
      z.literal('EPOCH'),
      z.literal('TIMELINE_RANGE'),
    ]),
    preservation: z.tuple([
      z.literal('IMMUTABLE_INPUT_MEDIA'),
      z.literal('PROXY_MASTER_MAPPING'),
      z.literal('VERSIONED_SEQUENCE_IDENTITY'),
    ]),
    operationBoundary: z.literal('DECLARED_RANGE_SCOPED_EDITABLE_OPERATIONS_ONLY'),
    deliveryBoundary: z.literal('DECLARED_OUTPUT_AND_IMF_SPEC_ONLY'),
  }).strict(),
  ceilings: z.tuple([
    z.literal('TOTAL_INGESTED_SOURCE_BYTES_AT_OR_BELOW_100_GB'),
    z.literal('AGGREGATE_RAW_SOURCE_DURATION_AT_OR_BELOW_FOUR_HOURS'),
    z.literal('NO_UNDECLARED_CODEC_CAMERA_COLOUR_OR_DELIVERY_PROFILE'),
    z.literal('NO_OPERATION_OUTSIDE_DECLARED_TIMELINE_RANGE'),
  ]),
  admission: z.literal('STOP_AT_FIRST_OF_TOTAL_INGESTED_SOURCE_BYTES_100_GB_OR_AGGREGATE_RAW_SOURCE_DURATION_FOUR_HOURS'),
  stopAtFirst: z.tuple([
    z.literal('RIGHTS_OR_EGRESS_GATE_FAILS'),
    z.literal('SOURCE_VERSION_STREAM_EPOCH_OR_RANGE_IDENTITY_MISSING'),
    z.literal('PROXY_MASTER_MAPPING_OR_INPUT_IMMUTABILITY_UNVERIFIED'),
    z.literal('REQUIRED_FAMILY_PROOF_MISSING_INVALID_OR_NON_REPRODUCIBLE'),
    z.literal('OUTPUT_OR_IMF_DECLARATION_OR_VALIDATION_MISSING'),
    z.literal('ARCHIVE_RESTORE_RELINK_REREAD_OR_RERENDER_VERIFICATION_FAILS'),
  ]),
  requiredFamilyIds: z.tuple([
    z.literal('agency.vfx.masks-mattes-roto-keying-tracking'),
    z.literal('agency.vfx.plates-exr-vfx-pulls'),
    z.literal('agency.colour.temporally-consistent-relighting'),
    z.literal('agency.finishing.conform-reconform-change-lists'),
    z.literal('agency.delivery.mastering'),
    z.literal('agency.delivery.declared-imf-class'),
    z.literal('agency.recovery.archive-restore'),
  ]),
  proofChainStages: z.tuple([
    z.literal('CALLER'),
    z.literal('DECISION_OWNER'),
    z.literal('FORM_OWNER'),
    z.literal('MUTATION_OWNER'),
    z.literal('STORED_STATE_REVISION'),
    z.literal('RENDERER'),
    z.literal('PROOF'),
  ]),
  sourceTruth: z.object({
    status: z.literal('RESEARCH_SOURCE_SURFACES_NO_OWNER_CERTIFIED'),
    observationIds: z.tuple([
      z.literal('api.editron-linked-route-exports'),
      z.literal('persistence.project-service-public-methods'),
      z.literal('proof.render-delivery-module-candidates'),
      z.literal('worker.job-module-candidates'),
    ]),
  }).strict(),
  currentStatus: z.object({
    implementation: z.literal('IMPLEMENTATION_OPEN'),
    sourceOwnership: z.literal('NO_OWNER_CERTIFIED'),
    relighting: z.literal('NO_PRODUCT_OWNER_OR_EXECUTABLE_CAPABILITY_FOUND'),
    movingMattesAndTracking: z.literal('EXPLICIT_CAPABILITY_GAP'),
    conformImfAndArchive: z.literal('PROFESSIONAL_PATHS_NOT_FOUND'),
    proxyMasterFoundations: z.literal('FOUNDATIONS_PRESENT_NOT_PROFESSIONAL_SYSTEM'),
    fullEnvelopeEvidence: z.literal('NOT_RUN'),
  }).strict(),
  openGaps: z.tuple([
    z.literal('RELIGHT_PRODUCT_OWNER_AND_EXECUTABLE_CAPABILITY'),
    z.literal('MOVING_MATTE_AND_TRACKED_FINE_CONTOUR_CAPABILITY'),
    z.literal('PROFESSIONAL_RECONFORM_CHANGE_LIST_IMF_VFX_PULL_AND_ARCHIVE_RESTORE_PATHS'),
    z.literal('FULL_100_GB_TOTAL_INGESTED_SOURCE_BYTES_FOUR_HOUR_AGGREGATE_RAW_SOURCE_DURATION_FIXTURE_AND_QUALIFIED_REVIEWER'),
  ]),
  capabilitySourceDeliveryRows: z.array(z.object({
    rowId: z.string().min(1),
    layer: z.enum(['CAPABILITY', 'SOURCE', 'DELIVERY']),
    declaredSubclass: z.string().min(1),
    currentSourceObservationIds: z.array(z.string().min(1)).min(1),
    eligibleForms: z.array(z.string().min(1)).min(1),
    requiredProofs: z.array(z.string().min(1)).min(1),
  }).strict()).length(7),
  declaredAgencyImfClass: z.object({
    classId: z.literal('AGENCY_IMF_DECLARED_CLASS_V1'),
    applicationConstraints: z.tuple([
      z.literal('ONE_DECLARED_AGENCY_APPLICATION_PROFILE'),
      z.literal('DECLARED_TIMELINE_AND_VERSION_IDENTITY'),
      z.literal('VALIDATED_PACKAGE_MANIFEST_REQUIRED'),
    ]),
    essenceCodecs: z.tuple([
      z.literal('DECLARED_PICTURE_ESSENCE_CODEC_AND_PROFILE'),
      z.literal('DECLARED_AUDIO_ESSENCE_CODEC_AND_PROFILE'),
    ]),
    audioLayouts: z.tuple([z.literal('DECLARED_AUDIO_LAYOUT')]),
    captionsSubtitles: z.tuple([z.literal('DECLARED_CAPTION_SUBTITLE_PROFILE')]),
    supplementalVersions: z.tuple([z.literal('EXPLICITLY_DECLARED_SUPPLEMENTAL_VERSION_SET')]),
    identifiers: z.tuple([
      z.literal('CONTENT_ID'),
      z.literal('COMPOSITION_ID'),
      z.literal('PACKAGE_ID'),
      z.literal('ESSENCE_ID'),
    ]),
    validator: z.literal('INDEPENDENT_DECLARED_IMF_VALIDATOR_REQUIRED'),
    status: z.literal('DECLARATION_ONLY_NO_IMPLEMENTATION_OR_CERTIFICATION'),
  }).strict(),
  proofRequirements: z.tuple([
    z.literal('EVERY_ROW_CALLER_TO_DECISION_OWNER_TO_FORM_OWNER_TO_MUTATION_OWNER_TO_RENDERER_TO_PROOF'),
    z.literal('FAST_DETERMINISTIC_CLIP_SEMANTICS_AND_SAFE_STOPS'),
    z.literal('RIGHTS_CLEARED_FULL_100_GB_TOTAL_INGESTED_SOURCE_BYTES_FOUR_HOUR_AGGREGATE_RAW_SOURCE_DURATION_FIXTURE'),
    z.literal('EXACT_PERCEPTUAL_AND_HUMAN_EVIDENCE_WITH_CORRECTION_TIME_AND_COMPLETE_COST'),
    z.literal('ISOLATED_COMPONENT_COVERAGE_IS_NOT_AGENCY_CLOSURE'),
  ]),
  explicitExclusions: z.array(z.object({
    exclusionId: z.string().min(1),
    disposition: z.enum(['LATER_FILM_POST_VARIANT', 'EXPLICITLY_INELIGIBLE']),
    statement: z.string().min(1),
  }).strict()).length(7),
  authority: z.object({
    declaration: z.literal('SUPPORTED_SUBCLASS_DECLARATION_ONLY'),
    implementationStatus: z.literal('IMPLEMENTATION_OPEN'),
    certified: z.literal(false),
    productionEligible: z.literal(false),
    runtimeMutationAuthorized: z.literal(false),
    readinessReceipt: z.literal('NOT_A_READINESS_RECEIPT'),
    catalogPromotion: z.literal(false),
  }).strict(),
  freezeHash: SHA256,
}).strict();

export type Agency100Gb4hV1SupportClassFreeze = z.infer<
  typeof agency100Gb4hV1SupportClassFreezeSchema
>;

export function parseAgency100Gb4hV1SupportClassFreeze(
  value: unknown,
): Agency100Gb4hV1SupportClassFreeze {
  const parsed = agency100Gb4hV1SupportClassFreezeSchema.parse(value);
  const { freezeHash, ...material } = parsed;
  if (hashCanonicalCap2ArtifactV1(material) !== freezeHash
    || hashCanonicalCap2ArtifactV1(material)
      !== hashCanonicalCap2ArtifactV1(agencySupportClassMaterial)) {
    throw new Error('CAP-2 v11 agency support-class freeze drift.');
  }
  return parsed;
}

export const AGENCY_100GB_4H_V1_SUPPORT_CLASS_FREEZE = deepFreeze(
  parseAgency100Gb4hV1SupportClassFreeze({
    ...agencySupportClassMaterial,
    freezeHash: hashCanonicalCap2ArtifactV1(agencySupportClassMaterial),
  }),
);

const reconciledEvidence = deepFreeze([
  {
    "path": "app/api/cron/recover-media-proxy-master-transcode/route.ts",
    "normalizedSha256": "e5c4bca1df8a5ab55fd3bbeec70d4b9587fc7aa04625257da688f65d84789251"
  },
  {
    "path": "lib/editron/services/project-service.ts",
    "normalizedSha256": "172356cbe89926d66d406273a5ab9e8a74a32edfb39a700cb1e71e6fc4b071d7"
  },
  {
    "path": "lib/editron/services/media-proxy-master-transcode-prepared-evidence-v2.ts",
    "normalizedSha256": "a8ee24f10eb539406985bd221fec04280a969c8298efc6ed6350f542c65d9661"
  },
  {
    "path": "lib/editron/services/durable-workflow-qstash-dispatch-v1.ts",
    "normalizedSha256": "0998ae86fb51d3cc2b2abdae819d5b560cddc27043220707333a02b59a159871"
  }
] as const);

const sourceSurfaceDelta = deepFreeze({
  priorPathCount: 231 as const,
  currentPathCount: 351 as const,
  addedPathCount: 120 as const,
  priorIdentifierOccurrences: 486 as const,
  currentIdentifierOccurrences: 636 as const,
  addedIdentifierOccurrences: 150 as const,
  changedSourceObservationCount: 4 as const,
  changedSourceIds: [
  "api.editron-linked-route-exports",
  "persistence.project-service-public-methods",
  "proof.render-delivery-module-candidates",
  "worker.job-module-candidates"
] as const,
});

const semanticDelta = deepFreeze({
  deltaId: 'source-surface.current-tree-reconciliation-v11',
  disposition: 'CURRENT_SOURCE_SURFACE_RECONCILED_CATALOG_STILL_EXCLUDED' as const,
  statement: 'The CAP-2 source extractor was rerun against the clean checked-out source tree. V10 remains the immutable 231-path historical baseline; V11 binds the 351-path, 636-identifier current surface, freezes the declared AGENCY_100GB_4H_V1 capability/source/delivery subclasses and proofs, and records four observation deltas without promoting any source to a capability or runtime authority.',
  evidence: reconciledEvidence,
  sourceSurfaceDelta,
  resolvedGaps: [
    'The current source extractor has been rerun and its four changed observation families are explicitly represented as a V11 delta.',
    'The immutable V10 manifest and source snapshot remain chained as the historical prior audit.',
    'Representative files from every changed observation family are hash-bound to the V11 issuance snapshot.',
  ] as const,
  remainingGaps: [
    'These broad, overlapping source observations remain research surfaces and do not establish capability ownership or certification.',
    'The five reconciliation domains still retain unresolved owner/source observations for later bounded work.',
    'No planner registry wiring or ProjectService mutation authorization is introduced by this reconciliation.',
    'No production certification, durable downstream proof chain or rendered proof is introduced by this reconciliation.',
    'The agency VFX, finishing and relighting ADR remains accepted scope with implementation open; V11 freezes the bounded declared subclasses and proofs but does not implement or certify them.',
  ] as const,
  catalogPromotion: false as const,
});

export const cap2CurrentTruthReissueAuditSchemaV11 = z.object({
  artifactType: z.literal('EditronCapabilityCurrentTruthReissueAuditV11'),
  schemaVersion: z.literal(11),
  authority: z.literal('RESEARCH_CENSUS_NO_RUNTIME_MUTATION'),
  status: z.literal('REISSUED_CURRENT_TRUTH_RESEARCH_ONLY'),
  priorAuditBinding: z.object({
    artifactType: z.literal('EditronCapabilityCurrentTruthReissueAuditV10'),
    manifestHash: z.literal(PRIOR_MANIFEST_SHA256),
    normalizedSourceSnapshotHash: z.literal(PRIOR_SOURCE_SNAPSHOT_SHA256),
  }).strict(),
  sourceBinding: z.object({
    branch: z.literal('infrastructure-improvs-+Editron'),
    commit: z.literal(CURRENT_COMMIT_V11),
    normalizedSourceSnapshotHash: z.literal(SOURCE_SNAPSHOT_SHA256),
    sourceSnapshotPathCount: z.literal(351),
    sourceObservationCount: z.literal(11),
    observedIdentifierOccurrences: z.literal(636),
    workingTreeEvidenceStatus: z.literal('CLEAN_BOUND_SOURCE_PATHS_AT_ISSUANCE'),
    reconciliationStatus: z.literal('RECONCILED_CURRENT_TRUTH_V11'),
  }).strict(),
  catalogBinding: z.object({
    catalogHash: z.literal(CAP2_FROZEN_CATALOG_HASH_V1),
    declaredOperationCount: z.literal(37),
    certifiedOperationCount: z.literal(0),
    productionEligibleOperationCount: z.literal(0),
  }).strict(),
  agencySupportClassFreeze: agency100Gb4hV1SupportClassFreezeSchema,
  semanticDelta: z.object({
    deltaId: z.literal('source-surface.current-tree-reconciliation-v11'),
    disposition: z.literal('CURRENT_SOURCE_SURFACE_RECONCILED_CATALOG_STILL_EXCLUDED'),
    statement: z.string().min(1),
    evidence: z.array(z.object({
      path: z.string().min(1),
      normalizedSha256: SHA256,
    }).strict()).length(4),
    sourceSurfaceDelta: z.object({
      priorPathCount: z.literal(231),
      currentPathCount: z.literal(351),
      addedPathCount: z.literal(120),
      priorIdentifierOccurrences: z.literal(486),
      currentIdentifierOccurrences: z.literal(636),
      addedIdentifierOccurrences: z.literal(150),
      changedSourceObservationCount: z.literal(4),
      changedSourceIds: z.tuple([
        z.literal("api.editron-linked-route-exports"),
        z.literal("persistence.project-service-public-methods"),
        z.literal("proof.render-delivery-module-candidates"),
        z.literal("worker.job-module-candidates"),
      ]),
    }).strict(),
    resolvedGaps: z.array(z.string().min(1)).length(3),
    remainingGaps: z.array(z.string().min(1)).length(5),
    catalogPromotion: z.literal(false),
  }).strict(),
  reissueGate: z.object({
    priorAuditChained: z.literal(true),
    sourceSurfaceReconciledAndReverified: z.literal(true),
    changedPathEvidenceBound: z.literal(true),
    historicalV10Preserved: z.literal(true),
    catalogAuthorityUnchanged: z.literal(true),
    runtimeAuthorityDenied: z.literal(true),
  }).strict(),
  runtimeAuthority: z.object({
    plannerRegistryWired: z.literal(false),
    plannerProjectMutationAuthorized: z.literal(false),
    productionCertificationGranted: z.literal(false),
  }).strict(),
  manifestHash: SHA256,
}).strict();

export type Cap2CurrentTruthReissueAuditV11 = z.infer<
  typeof cap2CurrentTruthReissueAuditSchemaV11
>;

export function parseCap2CurrentTruthReissueAuditV11(
  value: unknown,
): Cap2CurrentTruthReissueAuditV11 {
  const parsed = cap2CurrentTruthReissueAuditSchemaV11.parse(value);
  const { manifestHash, ...material } = parsed;
  if (hashCanonicalCap2ArtifactV1(material) !== manifestHash) {
    throw new Error('CAP-2 v11 manifest hash drift.');
  }
  if (hashCanonicalCap2ArtifactV1(parsed.semanticDelta)
    !== hashCanonicalCap2ArtifactV1(semanticDelta)) {
    throw new Error('CAP-2 v11 semantic delta drift.');
  }
  parseAgency100Gb4hV1SupportClassFreeze(parsed.agencySupportClassFreeze);
  return parsed;
}

export function assertCap2CurrentTruthSourcesMatchV11(): void {
  if (CAP2_CURRENT_TRUTH_SOURCE_PATHS_V11.length !== 351
    || CAP2_CURRENT_TRUTH_SOURCE_OBSERVATIONS_V11.length !== 11
    || CAP2_CURRENT_TRUTH_SOURCE_OBSERVATIONS_V11.reduce(
      (total, observation) => total + observation.observedCount,
      0,
    ) !== 636) {
    throw new Error('CAP-2 v11 current source coverage drift.');
  }
  if (hashNormalizedCap2SourceSnapshotV11(CAP2_CURRENT_TRUTH_SOURCE_PATHS_V11)
    !== SOURCE_SNAPSHOT_SHA256) {
    throw new Error('CAP-2 v11 current source snapshot drift.');
  }
  for (const evidence of reconciledEvidence) {
    if (hashNormalizedCap2FileV11(evidence.path) !== evidence.normalizedSha256) {
      throw new Error('CAP-2 v11 reconciled evidence drift: ' + evidence.path + '.');
    }
  }
  for (const evidence of [
    AGENCY_100GB_4H_V1_SUPPORT_CLASS_FREEZE.sourceBasis.acceptedAgencyAdr,
  ]) {
    if (hashNormalizedCap2FileV11(evidence.path) !== evidence.normalizedSha256) {
      throw new Error('CAP-2 v11 agency support-class source drift: ' + evidence.path + '.');
    }
  }
}

if (CAP2_CURRENT_TRUTH_REISSUE_AUDIT_V10.manifestHash !== PRIOR_MANIFEST_SHA256
  || CAP2_CURRENT_TRUTH_REISSUE_AUDIT_V10.sourceBinding.normalizedSourceSnapshotHash
    !== PRIOR_SOURCE_SNAPSHOT_SHA256) {
  throw new Error('CAP-2 v10 changed beneath the v11 reissue audit.');
}

const auditMaterial = {
  artifactType: 'EditronCapabilityCurrentTruthReissueAuditV11' as const,
  schemaVersion: 11 as const,
  authority: 'RESEARCH_CENSUS_NO_RUNTIME_MUTATION' as const,
  status: 'REISSUED_CURRENT_TRUTH_RESEARCH_ONLY' as const,
  priorAuditBinding: {
    artifactType: CAP2_CURRENT_TRUTH_REISSUE_AUDIT_V10.artifactType,
    manifestHash: PRIOR_MANIFEST_SHA256,
    normalizedSourceSnapshotHash: PRIOR_SOURCE_SNAPSHOT_SHA256,
  },
  sourceBinding: {
    branch: 'infrastructure-improvs-+Editron' as const,
    commit: CURRENT_COMMIT_V11,
    normalizedSourceSnapshotHash: SOURCE_SNAPSHOT_SHA256,
    sourceSnapshotPathCount: 351 as const,
    sourceObservationCount: 11 as const,
    observedIdentifierOccurrences: 636 as const,
    workingTreeEvidenceStatus: 'CLEAN_BOUND_SOURCE_PATHS_AT_ISSUANCE' as const,
    reconciliationStatus: 'RECONCILED_CURRENT_TRUTH_V11' as const,
  },
  catalogBinding: {
    catalogHash: CAP2_FROZEN_CATALOG_HASH_V1,
    declaredOperationCount: 37 as const,
    certifiedOperationCount: 0 as const,
    productionEligibleOperationCount: 0 as const,
  },
  agencySupportClassFreeze: AGENCY_100GB_4H_V1_SUPPORT_CLASS_FREEZE,
  semanticDelta,
  reissueGate: {
    priorAuditChained: true as const,
    sourceSurfaceReconciledAndReverified: true as const,
    changedPathEvidenceBound: true as const,
    historicalV10Preserved: true as const,
    catalogAuthorityUnchanged: true as const,
    runtimeAuthorityDenied: true as const,
  },
  runtimeAuthority: {
    plannerRegistryWired: false as const,
    plannerProjectMutationAuthorized: false as const,
    productionCertificationGranted: false as const,
  },
};

export const CAP2_CURRENT_TRUTH_REISSUE_AUDIT_V11 = deepFreeze(
  parseCap2CurrentTruthReissueAuditV11({
    ...auditMaterial,
    manifestHash: hashCanonicalCap2ArtifactV1(auditMaterial),
  }),
);

function deepFreeze<T>(value: T): T {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const nested of Object.values(value as Record<string, unknown>)) {
      deepFreeze(nested);
    }
  }
  return value;
}
