import { CaptionStyles } from "../types";

export const captionTemplates: Record<
  string,
  { name: string; styles: CaptionStyles; preview: string }
> = {
  classic: {
    name: "Classic",
    preview: "Clean & Professional",
    styles: {
      fontFamily: "font-sans",
      fontSize: "35px",
      fontWeight: 500,
      color: "#FFFFFF",
      textAlign: "center",
      lineHeight: 1.4,
      letterSpacing: "0.01em",
      textShadow: "2px 2px 4px rgba(0,0,0,0.6), 0 0 20px rgba(0,0,0,0.3)",
      padding: "12px",
      highlight: {
        backgroundColor: "rgba(59, 130, 246, 0.92)",
        color: "#FFFFFF",
        scale: 1.06,
        fontWeight: 600,
        textShadow: "2px 2px 4px rgba(0,0,0,0.4)",
        borderRadius: "6px",
        padding: "2px 8px",
        effect: "box",
        animation: "scale",
      },
    },
  },
  hustle: {
    name: "Hustle",
    preview: "Bold & Dynamic",
    styles: {
      fontFamily: "font-league-spartan",
      fontSize: "35px",
      fontWeight: 800,
      color: "#FFFFFF",
      textAlign: "center",
      lineHeight: 1.3,
      letterSpacing: "-0.02em",
      textShadow: "3px 3px 0 rgba(0,0,0,0.8)",
      highlight: {
        backgroundColor: "#FF3B3B",
        color: "#FFFFFF",
        scale: 1.08,
        fontWeight: 800,
        textShadow: "3px 3px 0 rgba(0,0,0,0.8)",
        borderRadius: "2px",
        padding: "4px 12px",
        effect: "pop",
        animation: "bounce",
      },
    },
  },
  medusa: {
    name: "Medusa",
    preview: "Modern & Sleek",
    styles: {
      fontFamily: "font-sans",
      fontSize: "32px",
      fontWeight: 500,
      color: "#FFFFFF",
      textAlign: "center",
      lineHeight: 1.3,
      letterSpacing: "0.02em",
      highlight: {
        backgroundColor: "rgba(34, 197, 94, 0.95)",
        color: "#FFFFFF",
        scale: 1.06,
        fontWeight: 600,
        borderRadius: "8px",
        padding: "4px 12px",
        effect: "box",
        animation: "scale",
      },
    },
  },
  minimal: {
    name: "Minimal",
    preview: "Simple & Clean",
    styles: {
      fontFamily: "font-sans",
      fontSize: "24px",
      fontWeight: 400,
      color: "#FFFFFF",
      textAlign: "center",
      lineHeight: 1.2,
      backgroundColor: "rgba(0,0,0,0.6)",
      padding: "4px 22px",
      highlight: {
        backgroundColor: "rgba(0,0,0,0.8)",
        color: "#FFFFFF",
        scale: 1.02,
        fontWeight: 500,
        padding: "2px 8px",
        borderRadius: "4px",
        effect: "none",
        animation: "none",
      },
    },
  },
  neon: {
    name: "Neon",
    preview: "Vibrant & Electric",
    styles: {
      fontFamily: "font-sans",
      fontSize: "35px",
      fontWeight: 600,
      color: "#FFFFFF",
      textAlign: "center",
      lineHeight: 1.3,
      textShadow:
        "0 0 10px rgba(255,255,255,0.9), 0 0 20px rgba(255,255,255,0.5), 0 0 30px rgba(255,255,255,0.3)",
      highlight: {
        backgroundColor: "rgba(139, 92, 246, 0.25)",
        color: "#F0ABFC",
        scale: 1.07,
        fontWeight: 600,
        textShadow:
          "0 0 10px rgba(240,171,252,0.9), 0 0 20px rgba(240,171,252,0.5), 0 0 30px rgba(240,171,252,0.3)",
        borderRadius: "8px",
        padding: "4px 16px",
        effect: "glow",
        animation: "pulse",
      },
    },
  },
  handwritten: {
    name: "Handwritten",
    preview: "Casual & Friendly",
    styles: {
      fontFamily: "font-serif",
      fontSize: "35px",
      fontWeight: 400,
      color: "#FFFFFF",
      textAlign: "center",
      lineHeight: 1.4,
      textShadow: "1px 1px 2px rgba(0,0,0,0.6)",
      padding: "8px",
      highlight: {
        backgroundColor: "rgba(34, 197, 94, 0.9)",
        color: "#FFFFFF",
        scale: 1.08,
        fontWeight: 600,
        textShadow: "1px 1px 2px rgba(0,0,0,0.4)",
        borderRadius: "8px",
        effect: "box",
        animation: "bounce",
      },
    },
  },
  retro: {
    name: "Retro",
    preview: "Vintage & Bold",
    styles: {
      fontFamily: "font-retro",
      fontSize: "29px",
      fontWeight: 400,
      color: "#FFD700",
      textAlign: "center",
      lineHeight: 1.2,
      letterSpacing: "0.02em",
      textShadow: "3px 3px 0 #FF4500",
      highlight: {
        backgroundColor: "#FF4500",
        color: "#FFD700",
        scale: 1.05,
        fontWeight: 400,
        textShadow: "2px 2px 0 #000000",
        borderRadius: "0px",
        padding: "2px 8px",
        effect: "pop",
        animation: "scale",
      },
    },
  },
  cinematic: {
    name: "Cinematic",
    preview: "Dramatic & Bold",
    styles: {
      fontFamily: "font-serif",
      fontSize: "38px",
      fontWeight: 700,
      color: "#FFFFFF",
      textAlign: "center",
      lineHeight: 1.3,
      letterSpacing: "0.03em",
      textShadow: "2px 2px 8px rgba(0,0,0,0.6)",
      highlight: {
        backgroundColor: "rgba(245, 158, 11, 0.9)",
        color: "#FFFFFF",
        scale: 1.06,
        fontWeight: 700,
        textShadow: "2px 2px 8px rgba(0,0,0,0.6)",
        borderRadius: "2px",
        padding: "4px 16px",
        effect: "box",
        animation: "scale",
      },
    },
  },
  gradient: {
    name: "Gradient",
    preview: "Smooth & Modern",
    styles: {
      fontFamily: "font-sans",
      fontSize: "35px",
      fontWeight: 600,
      color: "#FFFFFF",
      textAlign: "center",
      lineHeight: 1.3,
      background:
        "linear-gradient(135deg, rgba(255,255,255,0.1), rgba(255,255,255,0))",
      backdropFilter: "blur(8px)",
      padding: "12px 24px",
      borderRadius: "12px",
      textShadow: "2px 2px 4px rgba(0,0,0,0.3)",
      highlight: {
        backgroundColor: "black",
        color: "#FFFFFF",
        scale: 1.05,
        fontWeight: 700,
        textShadow: "1px 1px 2px rgba(0,0,0,0.2)",
        borderRadius: "8px",
        padding: "4px 16px",
        effect: "box",
        animation: "none",
      },
    },
  },
  future: {
    name: "Future",
    preview: "Sci-fi & Techy",
    styles: {
      fontFamily: "font-mono",
      fontSize: "34px",
      fontWeight: 600,
      color: "#E2E8F0",
      textAlign: "center",
      lineHeight: 1.3,
      letterSpacing: "0.02em",
      textShadow: "0 0 15px rgba(148,163,184,0.5)",
      padding: "12px",
      highlight: {
        backgroundColor: "rgba(14,165,233,0.15)",
        color: "#38BDF8",
        scale: 1.06,
        fontWeight: 700,
        textShadow: "0 0 15px rgba(56,189,248,0.6)",
        borderRadius: "4px",
        padding: "4px 16px",
        effect: "glow",
        animation: "pulse",
      },
    },
  },
};

// Default caption styles used when none specified
export const defaultCaptionStyles: CaptionStyles = captionTemplates.classic.styles;
